### PR TITLE
Makes the credits show our contributors instead of just TG

### PR DESCRIPTION
**Pull request by AffectedArc07**
Literally one line change, flattest please dont harm me from the commits.

:cl: AffectedArc07
fix: The credits now show our contributors. Does this mean I am in the credits. Does this mean you are in the credits?
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:)

### CODE REVIEW

**Comment by Ziiro** [comment]
:thinking:

I'm not sure how i feel about this

**Comment by AffectedArc07** [comment]
@Ziiro what do you see wrong with it?

**Comment by ike709** [comment]
IIRC they don't even have the credits on TG anymore.

**Comment by Wilchenx** [comment]
They don't have the credits on TG anymore because they could get DMCA'd due to different avatars people use

**Comment by SamHPurp** [comment]
Seems like a good enough reason to remove them here too.

**Comment by ike709** [comment]
I don't think we actually have enough contributors for that to become an issue. Also what happened to fair use?

**Comment by ike709** [comment]
And if it is _still_ an issue just remove images from the credits.

**Comment by SmokingKilz** [comment]
I don't really see us getting DMCA'd by anyone regarding the avatars, but if it's such an issue, as Ike suggested, just remove the avatars and only have the names.

**Comment by AffectedArc07** [comment]
Im gonna be honnest, if someone actually issues a DMCA takedown on a small SS13 server that isnt even for profit (iirc), they are gonna look stupid, also I agree with @ike709, stuff should fall under fair use. If we do get DMCA'd, I doubt much will happened apart from a cease and desist

**Comment by FlattestGuitar** [comment]
I don't see why a DMCA would be remotely relevant here. We're just using avatars that are already publicized through means different than the original content, 99% of the time likely without permission. Valve doesn't get DMCA'd for people's avatars in CS:GO. That'd be dumb.

I support this PR. While it's important that we recognize that everyone from the /tg/ station code team to Bjarne Stroustrup has helped create Oracle in one way or another, we just can't list all of them and it just makes for a mess that nobody wants to read.

**Comment by SamHPurp** [comment]
Assuming this is even what we want to do: The code isn't complete. You need to alter the re-mappings to be Oracle. (Also include me in the remappings please.)

Also, its worth noting with Andrew, that even after merge, this'll require running of the script server-side.

**Comment by AffectedArc07** [comment]
@SamHPurp this can be automated, as you can get travis to run the script every time a build is passed, which is what currently happens iirc. In terms of the mappings, I will check that now.

**Comment by SamHPurp** [comment]
As Flat approved before my requested changed, and that I'm happy with the change. I guess we'll give it a go. We can always disable credits in future.

**Comment by AffectedArc07** [comment]
Do we have this to be automated at the same time as the changelog generation?

**Comment by ike709** [comment]
This PR does not work. TG contribvutors still shown.

**Comment by AffectedArc07** [comment]
Look at the comment above, this wont work until the script autoruns, and it will keep the current contributors, I tested this locally and it did indeed work.

**Comment by SamHPurp** [comment]
Yep, we haven't ran it on the server yet, @ike709 

I tested locally before merge, and it was fine.

**Pull request merged**
