### PR TITLE
Fixes order of operations math errors with gas defines.

### PR DESCRIPTION
**Pull request by Ziiro**
:cl: TheDreamweaver
fix: The air around you grows cooler, as if what you once knew about atmospherics has changed ever so slightly...
/:cl:

https://github.com/tgstation/tgstation/pull/37116

### CODE REVIEW

**Comment by SamHPurp** [comment]
This was my favourite thing I saw then it was first noticed a few months ago.

I suspect there are wider balance tweaks required to counterbalance this fix... have TG done any yet?

**Comment by Ziiro** [comment]
Seems there was only one attempt and it got closed, not merged.

**Comment by Ziiro** [comment]
Wait nope here's one https://github.com/tgstation/tgstation/pull/37293

**Comment by SamHPurp** [comment]
Nice, lets get that committed along with this, and we'll merge and hope nothing breaks. ;)

**Comment by Ziiro** [comment]
I'll pull it in alongside this when I have time again, might be a few days

**Comment by Ziiro** [comment]
Seems we already had the defines. Done.

**Comment by Ziiro** [comment]
Also I would suggest testmerging this first obviously, as I'm only about 80% sure of it

**Comment by AndrewMontagne** [comment]
Tested successfully.

**Review by AndrewMontagne — APPROVED** [review]
LGTM

**Pull request merged**
