### PR TITLE
Ported locker and crate sprites from Goonstation2016

### PR DESCRIPTION
**Pull request by AndrewMontagne**
Also included some sprite tweaks of non-goon sprites by me for consistency. Many thanks to the Goonstation team for releasing their 2016 codebase under Creative Commons.

image
image
image
image image image image image

:cl: AndrewMontagne
tweak: Changed all the crate and locker sprites to be ones ported from Goonstation.
/:cl:

### CODE REVIEW

**Comment by AndrewMontagne** [comment]
Ignore the broken push CI integration, I accidentally pushed this to upstream instead of origin first time around.

**Comment by taukausanake** [comment]
They look so flat. And kind of disappointing. Why would you want to merge these?

**Comment by Ziiro** [comment]
Eh. You say flat, I say that they look sharp/clean, and if you can match the surroundings it works. We'll have to see how it ends up, but I like them

**Comment by SmokingKilz** [comment]
"They look so flat... Kind of disappointing." A+ constructive criticism there.

**Comment by taukausanake** [comment]
I am very constructive. And those are legitimate concerns. The current sprites have depth while these are just front and center boxes with a top portion to try and avoid their boxy-ness. Also, does everything need an outline now?

**Comment by SmokingKilz** [comment]
I appreciate that they are legitimate concerns and you can of course have them. But actually sharing what you think is wrong and how it could be changed would go a long way to get the product you think fits the best.

**Comment by FlattestGuitar** [comment]
I personally love the sprites. 👍 from me, those are far more in line with the rest of the stuff we have, considering /tg/'s 3/4 perspective.

**Pull request merged**
