### PR TITLE
(Ready for Review) Medbay Remap + Paramedic changes

### PR DESCRIPTION
**Pull request by Quantum-M**
**Ready for review and suggestions**

:cl: 
add: Metastation: has a new Paramedic closet and office.
add: Metastation: Quarantine Blastdoors to medbay.
tweak: Metastation: Major tweaks to medbay and its surrounding area.
/:cl:

Remaps the whole of medbay. Originally was meant to just be some paramedic stuff, I decided that a whole new remap would be nice for medbay for review and whatnot.

Requesting thoughts on:
*Reducing round start medbay supplies and remove the grenade building stuff from chemistry, to encourage chemistry to actually focus more on medicine.

Descriptions:

Medbay overall: Shows the connection of all pipes and wires
newmedbay
More spacious and less cluttered, it has quarantine blast doors added to it to all exits and windows out of medbay.

Auxiliary Storage
auxstorage
Only the CMO has access to the room. It has spare supplies, a spare paramedic space suit, and the CMO's space suit. It also has a closet with spare vox tanks and plasmaman tanks, along with a spare set of plasmaman suit and helmet.

Breakroom:
breakroom
Its a break room, its a room you take breaks in.

Chemistry
chemistry
Less isolated, hopefully, and without grenade parts that may hopefully encourage on making medicine instead.

Genetics
cloninggenetics
Nothing significant, besides less public.

CMO Office
cmosoffice
Less isolated, and more secured. Has privacy shutters and a button to activate the quarantine blastdoors, needs CMO access.

Cryogenics
cryogenics
Less cluttered and a bit more secured.

Examroom
examroom
Gives the advanced scanner its own room, and hopefully encourages some doctoring RP.

Medbay lobby
medbaylobby
Has the security outpost moved there to be less isolated and forgotten.

Morgue
morgue
More isolated, but the airlocks to it are more secured in which it has that wire protection plate.

Reception
reception
A more dedicated area for doctors to stay at, it has buttons controlling both of the airlocks.

Restroom.
restroom
A restroom in medbay, for restroom usage. Anyone can enter it.

Medbay Storage
storage
One extra doctor locker, but with less medkits.

Surgeries
surgery
Two surgery rooms with the exam room in the middle. More essential since the medical rework.

Treatment Center
treatment center
Has the usual two sleepers, along with a blood transfer area below it.

Virology.
virology
Less isolated and more attached to medbay. The atmospheric system its connected to could have any tank attached to it to poison the virology atmosphere.

Waiting Area
waiting area
A big waiting area for patients or visitors waiting for patients.

Paramedic
paramedic
Has their own office. The locker has paramedic clothing and supplies, along with one set of paramedic space suit.

Maintanance:
morguemaintanance
chapel maintanance
newmaintanance

### CODE REVIEW

**Comment by Quantum-M** [comment]
May I request a 'Do Not Merge' tag?

**Comment by Cactus2388** [comment]
I really like that there's no stockpile of medkits immediately next to the entrance. Overall looks like an improvement.

**Comment by Quantum-M** [comment]
Ready for review and suggestions

**Comment by kingoftheautism** [comment]
I would actually place firelocks in long waiting area so in case of fire less stuff would burn down

**Comment by miniusAreas** [comment]
I dislike the fact that viro is no longer in space. It makes it harder for antags with objectives to kill viros, as theres now a door and a soft wall, a single Rwall and doors, or a RWall, instead of a electrified window. Viro Sats windows made it a fair shot for getting the viro, allowing them to stay trapped and have to resort to sec / that brand new virus they just made. It doesnt feel fair in the slightest. I also dislike the lack of medikits we had before. Yes they got raided for "muh carry meds", but with our population spikes sometimes we burn through medikits in a hour and cargos dead / a dick / out of money. Also consider giving cryo back its 4 cryoxine beakers, as a paramed i like filling the beakers together.

**Pull request closed without merging**
