### PR TITLE
Adds some AI cores from vg, as well as a hologram.

### PR DESCRIPTION
**Pull request by Ziiro**
:cl: Duny-, Kokuten & Arthurdentist
add: Pirate, Fabulous, Terminal and Fuzz AI cores
add: "construct" and "alternate face"holograms
/:cl:
https://github.com/vgstation-coders/vgstation13/commit/4743404f15fcd7acc43b50bbe5a2c050e149d846
https://github.com/vgstation-coders/vgstation13/pull/1042
https://github.com/vgstation-coders/vgstation13/pull/1152
https://github.com/vgstation-coders/vgstation13/pull/1599
https://github.com/vgstation-coders/vgstation13/pull/5700

 (This one is actually quite long, but you get the idea)

dreamseeker_2018-01-05_22-23-09

### CODE REVIEW

**Comment by Ziiro** [comment]
Note: I had to add `icon = 'icons/mob/ai.dmi'` under the old ones, because of swapping between the ones in `goon/icons/mob/ai.dmi` and the ones *not* in there.

**Comment by FlattestGuitar** [comment]
Sorry for the late review, but those definitely should not be in a .dmi in the folder `goon`. Please move them to their own thing, as those sprites do need to be attributed to /vg/.

Cool with me otherwise.

Also, is that a Discord AI core?

**Comment by Ziiro** [comment]
@AndrewMontagne told me to put it in the goon folder, as that's our standard BY-SA-NC license folder. 🤔

**Comment by FlattestGuitar** [comment]
We'll have to make a new folder for that. The same just with a different name - just `icons/vg` is fine.

Otherwise we give the erroneus impression that the stuff comes from goon, when it doesn't.

**Pull request merged**
