### PR TITLE
Removes cat ears from the AutoDrobe

### PR DESCRIPTION
**Pull request by AndrewMontagne**
:cl: AndrewMontagne
del: Removed cat ears from the AutoDrobe
/:cl:

### CODE REVIEW

**Comment by Ziiro** [comment]
But how will we get those /tg/ bagil players now? 🤔

**Comment by Cactus2388** [comment]
if you want cat ears you should have to steal them from an ethari

+1

**Comment by Ralta** [comment]
Yes. Yes to the max.

**Comment by SmokingKilz** [comment]
Tbh I really don't care for the cat ears so I'm fine with keeping or removing them.

**Pull request merged**
