### PR TITLE
Get rid of portable chem dispensers, and make the normal chem dispensers constructable and upgradable

### PR DESCRIPTION
**Pull request by steamp0rt**
:cl: steamp0rt
refactor: Chem dispensers are now actual constructable machines
del: Portable chem dispensers. There was really no point of them, besides them being constructable, but now that normal chem dispensers can do that, there's no point of that anymore.
/:cl:

### CODE REVIEW

**Comment by Quantum-M** [comment]
Strongly disagree on the macro, chemistry is supposed to be tedious, not a quick process and it just makes it slightly more easier.

On the dispenser itself, the chemical and the energy the ones that start on the map are affected? Since a unupgraded chemical dispenser (the portable ones we have at the moment) are really weak on both chem numbers and energy numbers.

**Comment by FlattestGuitar** [comment]
I will not stand for copypasting ANYTHING into the game as a part of normal gameplay. No.

I'd be fine with recording recipes so you'd at least have to make something once during the round, but this is broken garbage that will only encourage people to exchange some minmax guides on the Discord. No.

**Comment by steamp0rt** [comment]
@Quantum-M Yes, ALL chem dispensers are now upgradable

@FlattestGuitar You can't make precise (read: good) macros without upgrades anyways

**Comment by Cactus2388** [comment]
Chemistry is already stupid easy and overpowered. Macros aren't needed.

**Comment by steamp0rt** [comment]
If this gets firmly denied, I'd still be willing to PR the upgradable chem dispenser alone.

**Comment by steamp0rt** [comment]
OK, I removed macros, and just left the upgradable chem dispensers

**Comment by steamp0rt** [comment]
Ready

**Pull request merged**
