### PR TITLE
Paramedic to have access to defibrillator.

### PR DESCRIPTION
**Pull request by Waseemq1235**
[Changelogs]: # (Please make a changelog if you're adding, removing or changing content that'll affect players. This includes, but is not limited to, new features, sprites, sounds; balance changes; map edits and important fixes)

:cl:
tweak: Paramedic now has access to the medical locker with the defribrillator
/:cl:

[why]: # (Paramedic is supposed to have access to defibrillators in order to revive likely dead bodies they get.:)

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
That's not right. You just gave all medical personnel access to the MD locker. I don't think that should happen; we don't want chemists or the viro looting their shit. I'd go for instead giving the paramedic his own defib or moving one of the preexisting ones to his place.

**Comment by Quantum-M** [comment]
Paramedic should probably be given a similar definitely to the one the CMO gets, but weaker and less reliable.

**Comment by kingoftheautism** [comment]
Yeah, maybe just give paramedic his own budget version of CMO defib. It's holding less charge for reviving AND can also zap

**Comment by Waseemq1235** [comment]
Closing this and opening a new PR for a small defib for the paramedic.

**Pull request closed without merging**
