### PR TITLE
Removes loud mode

### PR DESCRIPTION
**Pull request by AffectedArc07**
:cl: AffectedArc07
del: Command headsets no longer have loud mode
/:cl:

This feature is only ever used for annoyance, I am pretty sure no one enjoys it apart from the person speaking into the headsets, if you want to be loud use a megaphone, headsets should not have this ability built into the device.

### CODE REVIEW

**Comment by awesine** [comment]
how about instead of just removing it entirely you actually do something with it

**Comment by awesine** [comment]
like idk five second thought: the encryption key needed for loud mode is RnD locked

**Comment by awesine** [comment]
another 2 second thought: megaphones have a device in them that allows loud speech that can be inserted into headsets

**Comment by awesine** [comment]
add i ded tag

**Comment by awesine** [comment]
also i'm pretty sure you did this wrong, this doesn't remove the option but just makes it that turning it on/off won't actually do anything

**Comment by awesine** [comment]
not even that but this is only if you alt-click the headset so those that use it while its in their hand will still be able to turnon loud mode

**Comment by awesine** [comment]
and this doesn't even remove loud mode itself

**Comment by awesine** [comment]
do it properly pls

**Comment by Ziiro** [comment]
I don't agree. It's obnoxious, but sometimes that's the only way that command can be heard over the bullshit. If anything, size down the font so that it's still bigger than the rest, but not as big.

**Comment by AndrewMontagne** [comment]
@awesine Please don't spam pull requests with comments. If you want to add on to a comment, please edit it.

**Comment by AffectedArc07** [comment]
Thats the only flag that uses the variable `COMMAND` in the whole file, so I believe this works, waiting for input on the maintainers.

**Comment by awesine** [comment]
1: not done properly
2: doesn't actually remove loudmode
3: only removes it for those who alt click
4: add i ded tag

**Comment by Ziiro** [comment]
You'll have to remove the `command` tag from the headsets, as well as anything having to do with `use_command`.

Also this, where it actually applies the spans to the chat:

https://github.com/OracleStation/OracleStation/blob/c4001bcc574208461f8094f7e5309c5ec9adf998/code/game/objects/items/devices/radio/radio.dm#L207

**Comment by awesine** [comment]
still dont like this at all

**Comment by awesine** [comment]
and you still haven't removed the actual button to change it from the headset menu

**Comment by awesine** [comment]
this only removes it if you alt-click the headset

**Comment by SmokingKilz** [comment]
For the love of god, yes. This is not used as intended, people with it most of the time just screech into it half the time. If loud mode MUST exist, only give it to heads and put a cooldown on it.

**Comment by awesine** [comment]
Only heads have loud mode tho already

**Comment by FantasticFwoosh** [comment]
Well _Bryce Pax_ is most definitely going to miss out ( **/tg/** loudmouth)

**Comment by AffectedArc07** [comment]
@awesine **PLEASE** for the love of god, condense your comments and edit your old ones. The second commit removed the part which makes the text bold, someone else can contribute to my repo and remove the button from TGUI, because fuck TGUI, I aint touching it with a 10ft pole, I will ~~probably~~ definatley break it.

**Comment by awesine** [comment]
@AffectedArc07 then close the pull request if you don't even solve the problem

**Comment by AffectedArc07** [comment]
You are missing the point, this PR **DOES** solve the problem believe it or not, it removes the largeness of the text, it doesn't remove the UI portion because I will break the whole game UI if I try to touch it, I am letting someone skilled do that, and have even offered to include it into my PR.

**Comment by awesine** [comment]
Remove the UI portion or close the PR, as it's not getting merged without that, I can bet you.

**Comment by AffectedArc07** [comment]
I know it wont get merged. Act less like a 10 year old and I might actually put respect into your words. For the third time, I have stated that I dint want to touch TGUI, and would appreciate it if some else did it. You need to calm down a bit. Go take a walk outside before replying with 5 more comments.

**Comment by awesine** [comment]
then why did you make a PR then

**Comment by awesine** [comment]
>"haha umadbro"

**Comment by AffectedArc07** [comment]
Go ask the same question to **ANYONE** else who has work in progress PRs. Ziiro has his vox PR open even though it is incomplete, Many PRs start unfinished, like I said, you need to calm down, and condense your messages.

**Comment by awesine** [comment]
>opens pr immediately expecting it too be merged, even links it in OOC

>only fixes the problems when pointed out step-by-step how to fix the problem by someone else

>"b-but other people have their unfinished pr's open!" he says, not realizing those people actually work on their prs while its open and don't just wait for someone else to do the work for them

**Comment by AffectedArc07** [comment]
Nothing ever gets instant merged, thats how you get a failed codebase. I have said 4 times now I am not touching TGUI, because I will break the whole game.

**Comment by awesine** [comment]
you're still expecting someone else to fix your problem which is bad code practice

**Comment by AffectedArc07** [comment]
Making 10 messages and using a pull request comments as a chatroom isnt just bad practice, it looks terrible too. I **MIGHT** try TGUI when it isnt 11PM, goodnight.

**Comment by awesine** [comment]
>"y-you talk a lot and critiqued my PR u suck"

**Comment by AffectedArc07** [comment]
Im sorry, I dont speak crybaby, can you repeat that in stand english?

**Comment by awesine** [comment]
>"you critique my pr and tried to tell me what I did wrong, you're a loser lmfao"

**Comment by SmokingKilz** [comment]
Oi, can we try to keep in civil in here? What the hell is this, we look away for two seconds and this place turns into a war zone.

**Comment by AffectedArc07** [comment]
Today I will **ATTEMPT** to use TGUI, but no promises.

**Comment by AffectedArc07** [comment]
The actual UI option is gone now, I may or may not have completely broke TGUI, this should be ready to be discussed for merge or closure.

**Comment by scrubmcnoob** [comment]
I think the function should reside with megaphones and not a headset itself. Heads of staff also have their office announcement system for a reason.

**Comment by SmokingKilz** [comment]
I agree with scrub. Putting aside the problem loud mode gives us admins while trying to monitor chat, it's just -really- annoying and meme-y. As said, only people that should be screeching onto comms are people with megaphones.

**Comment by AffectedArc07** [comment]
@SamHPurp this no longer needs the WIP label

**Comment by SamHPurp** [comment]
@AndrewMontagne @FlattestGuitar this is one of the more important ones to merge if the code is good enough. Please take a look.

**Comment by AffectedArc07** [comment]
Thanks for that commit andrew, I had no idea TGUI needed to be built

**Pull request merged**
