### PR TITLE
CMO labcoat buff

### PR DESCRIPTION
**Pull request by FlattestGuitar**
# Old:

# New:

Discuss.

:cl: Flatty
tweak: Changes the color of the CMO labcoat. Now with 26% more fashion.
/:cl:

It also changes the Vox icons to match.

### CODE REVIEW

**Comment by Xantholne** [comment]
Cons: lol nothing
Pros: this is much better looking and matches their new beret dead on giving them a +20 to fashion for a bonus +6 to charisma rolls

**Comment by SmokingKilz** [comment]
I don't see why not, I like the colour.

**Comment by alexkar598** [comment]
Medical power creep

**Comment by DaveTheHeadcrab** [comment]
Honestly prefer the old one, the new one is a bit bright for my tastes.

**Comment by SamHPurp** [comment]
I personally prefer the old one, but not enough to try to veto this.

**Pull request merged**
