### PR TITLE
Removes cat ears, purrbation, and the anime button

### PR DESCRIPTION
**Pull request by Quantum-M**
:cl: 
del: Deletes kitty ears, anime button, and purrbation and anything related to these things.
/:cl:

Removes all kitty ear related items, including the icons, cuts out the anime making button, and utterly destroys the purrbation button and anything related to it, with extreme prejudice.

This sort of stuff is cringy and, frankly, rather creepy. It also has no place in a server attempting to achieve mid RP.

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
>removing the anime button

quantum

**Comment by Cactus2388** [comment]
I would understand removing it Icly but adminbus and Wizard should keep this

**Comment by ishitbyabullet** [comment]
Ah, trying to make rp serious. Noble goal. All you have to do now is plus maybe other things is
- Remove ethari. Why are there perfectly normal fox people? This isn't me being against people who like being animals. It's just odd to see perfectly normal fox people. The same could apply to lizardpeople as well.

- Remove skeletons. Besides being too spooky for most to tolerate, they're a meme basically.

- Remove abductors. How are grayy ayyliens serious?

- Remove cloth golems. They look like mummies so that can't be srs rp.

**Comment by Wilchenx** [comment]
>It also has no place in a server attempting to achieve mid RP

Remove all other meme admin buttons then, special yearly events and corgi fursuit.

Anyhow, because there is no other way of getting purrbation except for admin intervention, I think the admins know more about what direction they want the server to go than some rando from github.

**Comment by FlattestGuitar** [comment]
This is ridiculous!

What's next? Burning books?

Seriously, though, I think I support removing kitty ears and purrbation. The former gets picked by *those* kind of people, while the latter is constantly used by admins on the folks who beg for it, which probably shouldn't be an option.

The anime mode has nothing to do with that, though. I think it should stay.

Also where are my Ethari. 🦊

**Comment by AffectedArc07** [comment]
@FlattestGuitar not relevant to this PR, shut up with your furry species

**Comment by Xantholne** [comment]
jungle vulp hellhole

anime button is ok tho
fuck purrbation

**Comment by Captaincardgage** [comment]
Replace the purrbation with cluwnes instead. That way they can be valid without permission

**Comment by 81Denton** [comment]
>This sort of stuff is cringy and, frankly, rather creepy

Then why are Ethari in game 🤔

**Comment by SamHPurp** [comment]
@81Denton @ishitbyabullet Ethari aren't playable on Oracle for nearly 2 months now, but okay.

**Comment by Quantum-M** [comment]
While Ethari may seem something along of the lines of "furries", at least they aren't literally some human with a cat tail and ears stabled to them.

**Comment by SmokingKilz** [comment]
+1 to removal of cat ears and purrbation, -1 to removal of the anime button, it's simply there as a meme and I do not see any reason to remove as only us admins have access to it and it's only used in where specific moments, usually end of round.

**Comment by ishitbyabullet** [comment]
@SamHPurp Fair point however the PR plans to remove, not make it unplayable.

**Comment by RogueSteampunker** [comment]
Not shown: OP screaming and squealing in their anti-furry defense closet for 20 minutes before posting.

Just saying, seems a fair bit silly that cat ears are what breaks the apparent rp camel's back, and how your only other reasoning is that you find them creepy.

Jusssstttt saying

**Comment by FlattestGuitar** [comment]
We're already spending far too much time discussing this. I don't think it's a big issue, and, frankly, the only reason people use those ears is for *that* reason, and I don't think it can sensibly be justified within the world. Call me a crusader.

Next up, Unathi.

**Pull request merged**
