### PR TITLE
Ports Paradise SecHUD Icons

### PR DESCRIPTION
**Pull request by Joseph-Case**
Ports the paradise HUD icons, as I generally find they are nicer than the TG ones.
Examples:
Assistant:
image

Head of Security:
image

All Status Icons (Sec hud, medical hud, tele+chem implants, loyalty):
image

:cl: AffectedArc07
imageadd: Added Paradise HUD Icons
/:cl:

### CODE REVIEW

**Comment by AndrewMontagne** [comment]
@FlattestGuitar @SamHPurp Can we get review on these please?

**Comment by SamHPurp** [comment]
I guess I'm not against it, but I kinda like TGs.

**Comment by Joseph-Case** [comment]
@SamHPurp You find the TG mindshield/loyalty thing better? I can barely tell when people are shielded, especially when all the roles that are meant to have mindshields have mainly blue icons

**Comment by SamHPurp** [comment]
Can you provide screenshots of TGs so we can side-by-side them?

I just find the giant green Paradise dot ugly as fuck.

**Comment by Joseph-Case** [comment]
@SamHPurp will get one, Also the captain icon is only a [?] because I had the ID in the sec records when I was adding a wanted status, I cant get a picture of it with an ID in if needed, as for the picture here it is:
image
Literally the only way to tell if they are mindshielded/loyalty implanted is by a 1 pixel blue ring around the badge

**Comment by FlattestGuitar** [comment]
Personally, I feel there are many icons in both sets that are *shit*, but in the end I really like /tg/'s version more. I think we have some room to do something pretty and more modern than a giant green blob. A pretty animation on a dude would be incredible. For now, I'd rather we stuck with /tg/'s than switched to Para's.

Sorry for taking so long to respond.

**Comment by SamHPurp** [comment]
Thats essentially where I am with it too..

I agree with you @Joseph-Case that it could be better. I just think Paradise's green dot solution is worse, rather than better.

Something we could develop/design ourselves rather than just port perhaps?

**Comment by Joseph-Case** [comment]
Ok, I see your point.
I will try to think of a better way to identify mindshields

**Comment by Joseph-Case** [comment]
If I could figure out directional sprites, mindshielding could be done the same way as that genetic effect which gives an orange glow around the sprite

**Comment by SamHPurp** [comment]
As we discussed, we agree it could be done better, but not really good with Para's way.

Entirely encourage you to submit a new PR with a new way of identifying this!

**Comment by Spartan6** [comment]
*scream

**Pull request closed without merging**
