### PR TITLE
Removes language menu for ghosts.

### LINKED ISSUE #26: Language button visible when a ghost
Forgot to get a screenshot, but... ghost or aghost, and you've still got the Languages button visible and clickable as a ghost.

I know this was recently edited, so must be to do with that PR.

### PR DESCRIPTION
**Pull request by AndrewMontagne**
:cl: AndrewMontagne
fix: Removed language menu for ghosts.
/:cl:

Edit by Purpose:
Fixes #26

### CODE REVIEW

**Comment by AndrewMontagne** [comment]
[Fix language button being visible while ghosted.](https://trello.com/c/hwjM71wt/68-fix-language-button-being-visible-while-ghosted)

**Comment by Birdtalon** [comment]
I mean, yeah by all means. But I'm not sure why this started appearing suddenly as this file hasn't been recently modifed.

**Comment by AndrewMontagne** [comment]
@Birdtalon The language menu was hidden beneath the ghost GUI. :^)

**Comment by Birdtalon** [comment]
Oh my 😱

**Pull request merged**
