### PR TITLE
Set default client FPS to 60.

### PR DESCRIPTION
**Pull request by AndrewMontagne**
Does exactly what it says on the tin.

:cl: AndrewMontagne
tweak: Set default client FPS to 60
/:cl:

### CODE REVIEW

**Comment by AndrewMontagne** [comment]
[Set client FPS to 60](https://trello.com/c/jdSgDqI4/66-set-client-fps-to-60)

**Comment by SamHPurp** [comment]
Are we certain this isn't going to be breaking things?

**Comment by AndrewMontagne** [comment]
@SamHPurp As far as I am aware, the values of the object always get overwritten when they're loaded in from the persistent store. This is just the default of value upon construction, so if nothing gets loaded in, this is what the get. (See code/modules/client/preferences_savefile.dm:219)

**Comment by FlattestGuitar** [comment]
Upon further inspection of the code, I have found this way of soliving things to be optimal. #10 was wrongly closed. </3

LGTM.

**Pull request merged**
