### PR TITLE
Ported device sprites from CEV Eris.

### PR DESCRIPTION
**Pull request by AndrewMontagne**
image

Left to right:
- T-ray Scanner
- Atmospheric Analyzer
- Hand Teleporter
- Medical Scanner
- Mining Scanner
- Pinpointer

:cl: AndrewMontagne
imageadd: Ported device sprites from CEV Eris.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Not a fan of the pinpointer, to be honest. Everything else is great.

**Comment by SamHPurp** [comment]
@FlattestGuitar pin pointer when animated looks OK actually. Can we get a gif of the pinpointer in action, that might potentially change your mind.

**Comment by AndrewMontagne** [comment]
@FlattestGuitar @SamHPurp top row, ignore colours of other devices
image

**Comment by FlattestGuitar** [comment]
>:C

**Pull request closed without merging**
