### PR TITLE
Adds wigs to lizards

### PR DESCRIPTION
**Pull request by Ziiro**
:cl:
add: Lizards can now have hair
/:cl:

[Vote now on your phones](https://www.youtube.com/watch?v=PuOfncGJuZ8)

### CODE REVIEW

**Comment by SamHPurp** [comment]
No.

**Comment by Keluandrie** [comment]
No.

**Comment by Ziiro** [comment]
Use the thumbs you cretins

**Comment by Keluandrie** [comment]
No. Also make it take up the hat slot and it'd be solid. I still would prefer wigs require scalping, but I digress.

**Comment by FlattestGuitar** [comment]
Why would lizards have hair

**Comment by Ziiro** [comment]
Why would lizards be bipedal and be on a space station

**Comment by FlattestGuitar** [comment]
Fair point.

**Comment by SamHPurp** [comment]
As we discussed on Discord, this doesn't fit our vision for what we want for Unathi, or promote what we necessarily want to promote.

Customization of your toons is obviously really important, but simply adding the 'hair' flag and calling it a wig doesn't cut it in this instance.

**Comment by FantasticFwoosh** [comment]
Porting over [actual wig items from /tg/station](https://github.com/tgstation/tgstation/pull/31304) as a roundstart inventory thing for races including lizards would accommodate this @Ziiro better than giving them hair

Especially in the case of concealing the congenital baldness of many people in command positions under increasingly elaborate hats.

**Pull request closed without merging**
