### PR TITLE
Soft removed the Clown and Mime

### PR DESCRIPTION
**Pull request by ConflagratedCanine**
[Changelogs]: # 
🆑 
del: Removed the Clown and Mime, including all references to them in the code.
tweak: Scattered clown/mime gear across maintenance in OmegaStation.
tweak: Added "abandoned offices" to OmegaStation for the clown and mime respectively.
/:cl: 

Removes the Clown and Mime from Oracle to help assist the role-playing environment, and relegate the assistant nonsense to assistants, instead of giving them a dedicated role.

There has been much discussion on the Discord regarding their possible removal, and so far no defense other than "They're a must!" has arisen. Oracle wishes to have a unique stake in the SS13 server list, and this is the easiest and cleanest solution to helping enforce an MRP environment. 

Plus a dedicated assistant can be an unofficial clown/mime if they like.

### CODE REVIEW

**Comment by scrubmcnoob** [comment]
We want to be unique yes, but I feel this isn't the right step. RP doesn't always need to be seriousness, it should be immersive. I find these roles to be quite immerse with rest of the ss13 universe.

**Comment by SamHPurp** [comment]
So I'm probably against this.

However, I'd really like to hear fully formed arguments on both sides of this.

**Comment by Ziiro** [comment]
Per the discussion in discord, I feel it necessary to leave my feedback here:

Yes, I'll concede that the clown is often a magnet for LRP shittery. That being said, I do feel like they are sort of important for the experience. They add a level of silliness that doesn't come from much else in the game. People will argue they can't be removed, and they're integral to the SS13 experience. To a degree, I think that's true; because they kind of set the tone for everything else.  They're silly. Everything is silly. To remove them would definitely put a more serious bent on everything that suddenly makes a lot of other things out of place. Space Carp? Space Wizard Federation? Medical Robots with Lollipop guns?

Also some of everyone's favorite/best SS13 stories involve clowns.

From a lore perspective, I think having a "Corporation Approved Morale Manager" (perhaps a **C**ORPORATE **L**ICENSED **O**WNED & **W**ANTON **N**INCOMPOOP™) could work. Within **strict** guidelines, or facing severe consequences.

I think if you want shitters less often, make the person have to be really dedicated to being the clown: More failures in things they can do. Cluwne them if they are being bad (with removal of the idea of Cluwne=Valid, they just get to suffer with their new curse.). Include inherent, uncurable brain damage.

**Comment by Cid777** [comment]
> They add a level of silliness that doesn't come from much else in the game. 

Is contradicted by:

> They're silly. Everything is silly. To remove them would definitely put a more serious bent on everything that suddenly makes a lot of other things out of place. Space Carp? Space Wizard Federation? Medical Robots with Lollipop guns?

And for those examples:
     - Space Carp are a bit weird, but I'd argue they damage the roleplay atmosphere less than Clowns
     - Wizard rounds are more lighthearted than normal ones, they're not meant to be taken too seriously
     - There's actually been talk of removing the lollipop guns

> People will argue they can't be removed, and they're integral to the SS13 experience.

This isn't a defense. The clown isn't sacrosanct.

> From a lore perspective, I think having a "Corporation Approved Morale Manager" (perhaps a CORPORATE LICENSED OWNED & WANTON NINCOMPOOP™) could work. Within strict guidelines, or facing severe consequences.

This is more reasonable than a clown, but you probably _meant_ a clown here.

**Comment by Ziiro** [comment]
>Is contradicted by:

Well, I mean that clowns "Set the baseline" to that, and everything else works _because_ of the clown.

Just want to add: I have no defense for the Mime. I've seen maybe _one_ entertaining one, and can't really find a way to justify them.

**Comment by Cid777** [comment]
> Well, I mean that clowns "Set the baseline" to that, and everything else works because of the clown.

Do we know that this is the case? I understand why you'd argue it, but are there servers who (for example) remove clown but keep wizard, and are worse off for it _because_ you can't point to the clown as a baseline?

**Comment by ConflagratedCanine** [comment]
Removing other sillier elements over time doesn't sound like a net negative to be honest.

As for the Clown and Mime, they naturally attract a lot of terrible players that view it as a screw around role - unlike the assistant, however, the general consensus regarding the clown and it's affects on the culture of SS13 means it gets ignored when it ruins a round for someone by kidnapping them, slipping them out an airlock, or generally other obnoxious behaviors that would at least get an assistant handcuffed.

There are two approaches: Enforce a strict SOP that prevents the clown from harming any crew physically, psychologically, fiscally, or socially, and actually enforce it instead of hiding behind "Well it's MRP" but never expanding on the roleplaying thresholds that the clown somehow remains immune to. 

Readily blacklist them if they start harassing crew or engage in wonton banana warfare, jobban as soon as their "hilarious job takeover" results in medical malpractice. Hold them to the same standards as Security, who have to deal with the clown as a regular headache.

_or_

Remove the role entirely, and relegate it to some cute accessories and references int he lore and station texts. Players can still be perfectly silly, but there is no longer a goof-magnet that unfortunately attracts the worst players, and the administration doesn't have to waste time parsing ahelps and divining the context of the pranks and deciding if it had a negative impact on the player.


I do not believe that there are enough good clown players to justify keeping the role and tolerating all the awful experiences a bad clown produces for a larger number of players.

**Comment by ktoma36** [comment]
Having main'd clown myself as well as mime for a good while I can say that there are too many things you would lose by removing them. I love being able to make people's rounds in the silliest ways when playing one of the two, putting others enjoyment above my own. 

For clowning. It takes a certain person playing clown to make it enjoyable for not just themselves but to the crew. If someone is acting like a shitter as a clown then they tend to act like shitters in other jobs they play, just that its brought to more attention cause they are the clown. Good clowns strive to try interesting gimmicks, or at least attempt to be funny even at their own expense. 

For miming. Mimes are harder to play than a clown given that they are supposed to be the counter entertainment to the clown's wackyness. A proper mime is amazing, and if you want examples I can give stories. Using /me is an art and a tool, people who abuse it should be shunned and those that dont are simply are not playing mime to its full potential. Mimes that talk are no mimes at all.

Right now we are all coming from different codebases and servers. I mainly play on paradise myself where I have seen plenty of good and bad clowns/mimes. I have also played on some LRP servers as well like Hippie and TG where shitters rule the block with the clown coming out on top as the biggest one of them all (well perhaps second shitter to the Captain). Right now this server is in its infancy, we are setting the precedence for every player after us. I think we as a responsible community can enforce a higher standard on the clown and mime roles without putting the axe to them.

**Comment by ktoma36** [comment]
I have an interesting suggestion, put a high time lock on clown and mime roles. Put it up there with command and synthetic time locks, perhaps even higher. If we are worried about newcomers flocking to the mime and clown role with the intent to ruin rounds simply make it take dedication to play. Or we could adopt a karma system like Paradise has, making clown and mime roles a special thing reserved to those who have proven they are willing to make the round interesting even at their own expense.

**Comment by Ziiro** [comment]
>Do we know that this is the case? I understand why you'd argue it, but are there servers who (for example) remove clown but keep wizard, and are worse off for it because you can't point to the clown as a baseline?

I actually went looking for info on this. It seems Aurora, Bay, and CM*(Let's be honest CM is barely SS13) have removed clown. Bay seems to have removed them completely, while Aurora still has them in both mechanics and lore. (Although they have expanded on it to different schools). I can't speak for the state of the server, however - and it's HRP, not sure how applicable it would be.

>Removing other sillier elements over time doesn't sound like a net negative to be honest.

I'm not sure starting from the /tg/code with this in mind is at all a good place to be. There's a lot silly here.

I'm very much behind the idea of timelocking clown (and mime, I guess), and viewing it with greater scrutiny, however.

**Comment by Cid777** [comment]
> I love being able to make people's rounds in the silliest ways when playing one of the two, putting others enjoyment above my own.

Excellent, but is being a clown necessary to do this?

> For clowning. It takes a certain person playing clown to make it enjoyable for not just themselves but to the crew.

Correct.

> If someone is acting like a shitter as a clown then they tend to act like shitters in other jobs they play

It's possible this is the case, but I'm not sure it is.

> just that its brought to more attention cause they are the clown.

This is also the case with "good" things they do.

> I have an interesting suggestion, put a high time lock on clown and mime roles. Put it up there with command and synthetic time locks, perhaps even higher. If we are worried about newcomers flocking to the mime and clown role with the intent to ruin rounds simply make it take dedication to play.

But the thing is, new players _aren't_ the problem. It tends to be regulars that play clown, and even if that wasn't the case, Clown _existing_ is the problem. It lowers the overall roleplay atmosphere.

> Or we could adopt a karma system like Paradise has

As far as I know there's no plans for this, and no staff member wants this, though another staff member could correct me if I'm wrong.

> making clown and mime roles a special thing reserved to those who have proven they are willing to make the round interesting even at their own expense.

Karma doesn't really show that you're willing to do this, it only shows that you've been noticed for something.

**Comment by imsxz** [comment]
How does the clown even ruin immersion in ss13? Because it's not *realistic*? Or do the undesirable players that clowns tend to attract (according to personal anecdotes from a couple people) remove immersion?

If that's the case, I could make a convincing case that lizards/dogbeasts attract players that I don't like, and aren't *realistic*, therefore they should be removed as well.

If it isn't the case that realism isn't the issue here, but that clowns retract from the ss13 universe that we're trying to stay immersed in, then what exactly *is* the ss13 universe supposed to feel like? I've always been under the impression that the overall environment is supposed to have a silly and chaotic nature to it...

**Comment by Cid777** [comment]
> How does the clown even ruin immersion in ss13? Because it's not realistic?

Not that it's unrealistic, I don't think. It's that the clown is out of place in the setting.

> If that's the case, I could make a convincing case that lizards/dogbeasts attract players that I don't like, and aren't realistic, therefore they should be removed as well.

Whataboutism. Those things also being terrible doesn't mean this step can't be taken to improve things.

> If it isn't the case that realism isn't the issue here, but that clowns retract from the ss13 universe that we're trying to stay immersed in, then what exactly is the ss13 universe supposed to feel like?

That depends entirely on the server, and admittedly, I don't think we know _exactly_ what Oracle's meant to feel like. "MRP" is extremely vague, but we do intend to be higher than Paradise.

**Comment by Birdtalon** [comment]
controversial

**Comment by FlattestGuitar** [comment]
The issue I see with the Clown and Mime roles is that most of the time they're completely irrelevant to whatever is going on the station, meaning they don't contribute to a round's progress very much. Two weeksa go during our playtest we had a traitor going on a killing spree, with the clown just playing their bikehorn as they watched the guy mow down ten people. Honk honk.

I *have* seen clowns played in a fun and interesting manner, but those are an incredibly rare sight on Paradise and other servers I've tried. Most of the time it's using the same tired gimmicks of breaking into places, slipping people for no reason and antagonizing people who haven't done anything to you.

As far as I see, removing the clown and mime will be a net positive, but there are a lot of people who simply feel that the two jobs are integral enough to SS13 that this will heavily impact the way they perceive our server in a negative manner. As silly as this is, we want a fun server, but it can't be empty.

**Comment by Birdtalon** [comment]
There are things which need to be addressed in the PR itself; however I will add my argument into the discussion.

As a player personally am not bothered about having the Clown or Mime or not, I don't play them, or only play them to mess around.

However I question whether it's a good idea to remove them for the health of the server. As a headmin I have to think about the community at large, and there are a lot of players who enjoy the roles. Maybe not enough to stop them from playing on our server, but the removal of the Clown and Mime is a contentious issue at the best of times.

Several arguments have been raised that they do not add anything to the round; however I would ask why this is a problem specifically, I don't see why every role has to "add" to the round in some meaningful way. Some people just enjoy goofing off and these roles provide a certain opportunity to just be a jerk, and is that such a bad thing? While the roles do not add anything significant, I would also argue that they do not detract anything significant either. Clown or mime notwithstanding, people will always be slipped, areas will always be broken into, graffiti will always be painted.

I do agree with some that the clown and mime do not really fit the setting, and in a perfect world it would be good if they were never here; however the "integral to SS13" argument is not invalid entirely. Player perception is very important, especially if we are trying to attract players from other servers.

I think that removal of these would paint us in a negative light as a "no-fun-allowed" server at this early stage and for that reason I am against this change.

**Comment by ConflagratedCanine** [comment]
>would ask why this is a problem specifically

An assistant is someone that arrived late to the round, or didn't get the role they wanted - so they'll either goof off, go SSD,attempt to assist the role they wanted in some fashion, or become greytide.

The Librarian disappears into maintenance, plays like an assistant, or (rarely) sticks around their assigned station and hosts events for the weirdos that ran out of things to do.

The Psychologist disappears into maintenance, applies medical care anyway, or acts as a roleplay "punishment" role for security when they want to get an obnoxious crewmen off their hands.

None of these add anything to the round, but often,  _the _Clown__ behaves in a manner that negatively impacts the experiences and job performance of other crew, or otherwise becomes needlessly hostile to players that refuse to tolerate their previously approved hi-jinks.
The only other role with a similar behavior streak is the assistant, which **are** defensible as players need a dump role that has an opportunity for them to contribute to the station, or otherwise get a job reassignment into the department they wanted, if not something silly or niche like Pizza Delivery.

I thoroughly do not believe that the positive interactions folks have had _playing as_ or _with_ clowns outweighs the negative experience of others. Too often they end up being a detriment to crew safety, or begin greytiding without much recourse from security or any authority due to the perceived nature of the role, while an assistant attempting similar destructive behavior gets harmbatoned or thrown in a cell to go SSD for ten minutes.

You may not enjoy the idea of removing the clown, but that is not the only solution - Enforce a much stricter SOP. You want to be the rare exception of good clowning? Great! _Earn it__. Create a server where the clown isn't just shoving people over and calling them racial slurs, or breaking into Robotics five rounds straight to make a mech for themselves - rather than hide behind the MRP label, pointing to the clown as the low quality roleplay exception.

**Comment by SamHPurp** [comment]
OK So, aside from the fact that this PR is missing all sorts of elements that would need to still be removed/changed to even remotely make this viable... The number one arguement for this is a playerbase issue, not a code one, as admitted by the PR author.

They serve as entertainers, to provide the punchline to an absurd situation. Much like Antagonists where they job is to make the round interesting - the clowns job is to make the round amusing or entertaining.

Does TGcode have a bunch of tools which lend themselves to shittery? Yes.

Are more often than not, Clowns not even trying to be funny, and are instead shit heads? Yes.

Is straight removal of them the right, or interesting thing to do? No.

-----

Alternative proposals, some may not be great ideas, but at least they are ideas:

- Remove the clowns musical horn from him at roundstart, that honk music every shift is fucking repetitive. Instead add as loot in space / lavaland, and make it so only Clowns can use it - so they bring it back for them.

- Remove the PDA's slipping capability, requiring them to always use bananas.

- Most clumsy fail rates are at 50%, increase the fail chance a bit.

- Remove the clown and mime from OmegaStation, you've got reduced population anyway, focus the small pop on actual contributing roles.

- Add to the number of things that clumsy gene interacts with.

-----

As the PR is at the moment, will not be merged in its current state.

**Comment by scrubmcnoob** [comment]
> Remove the clowns musical horn from him at roundstart, that honk music every shift is fucking repetitive. Instead add as loot in space / lavaland, and make it so only Clowns can use it - so they bring it back for them.

@SamHPurp looks like this is the route we're taking? Hopefully it is.

**Comment by SamHPurp** [comment]
@scrubmcnoob we pretty much agreed on that point.

Discussion on alternative points may exist - but I have added that point in particular into Trello.

**Comment by EldritchSigma** [comment]
Can we remove the Clunwe spell for wizards? Or make that clunwe a different, cureable one from the regular admin punishment clunwe? Cause that fucking spell is low RP bullshit, same for horsemask and transformation spell into lesser (read useless) forms like chicks (chicken).

**Comment by SamHPurp** [comment]
As discussed on Discord at length, this won't be the route we'll be taking. We'll have some followups in future (Feel free to check Trello etc) to address some of the initial concerns that spurred this PR.

Any questions, drop em here or find me on Discord.

**Pull request closed without merging**
