### PR TITLE
Slime People and Pod People buffs.

### PR DESCRIPTION
**Pull request by FlattestGuitar**
Mostly just reverts my old changes made in #16.
:cl: Flatty
add: Slime People can split now. Get that mitosis going.
tweak: Pod People heal 50 times as fast now. Get that photosynthesis going.
/:cl:

I didn't test this, because I'm lazy.
I actually didn't even compile this.
It's here on the offchance that there are no errors, which there probably are.

### CODE REVIEW

**Comment by scrubmcnoob** [comment]
compile it like the potatoes you till daily

**Comment by SamHPurp** [comment]
ye, lets do it

**Comment by FlattestGuitar** [comment]
Would be great if someone ported https://github.com/tgstation/tgstation/pull/34166 somewhere down the line. That makes the whole thing a bit more interesting on top of it all.

**Comment by scrubmcnoob** [comment]
Sure, I'll get around to it @FlattestGuitar

**Pull request merged**
