### PR TITLE
Disables roundstart Ethari

### PR DESCRIPTION
**Pull request by ike709**
:cl: ike709
del: Ethari are disabled until someone makes them not a reskin.
/:cl:

[why]: I've gone on countless rants about why I think Ethari are terrible. Need I repeat myself?

Alternative to #587 

And yes I'm aware this won't actually update the config.

### CODE REVIEW

**Comment by Ziiro** [comment]
config change, do not merge, etc

**Comment by Ziiro** [comment]
Off the top of my head, here's what we could do to make them unique

1) Make them *actual mutants* and have them spawn with a random mutation
2) Can take a wider range of cold temperatures, but overheats at a lower threshold
3) Make them slightly faster? More robust? More unarmed damage? But give them `NOGUNS`

**Comment by ike709** [comment]
4. Port traits and force pacifism on them.

**Comment by Cactus2388** [comment]
5. Inability to use guns because dog hands

**Comment by scrubmcnoob** [comment]
If traits were ported, I could see that being reasonable among other things.
Disable for now though until such a PR comes to life as stated in the other PR.

**Comment by SamHPurp** [comment]
Scored out of 5 in terms of 'do I like/care?'

1. 3

1. 1

1. 2

1. 5

1. 5

Some of these are already stronger than the translation thing.

**Comment by ike709** [comment]
Still a fan of disabling Ethari to hopefully motivate someone to actually do one of those things.

**Comment by Ralta** [comment]
For what it's worth, we discussed species (Ethari included, of course) yesterday and have some ideas on where to go with them. Hopefully once we have a good way of sitting them in Oracle from a lore perspective,  they'll be more acceptable.

**Comment by ike709** [comment]
\>trying to justify a reskin race with lore

Lore is irrelevant. What unique *gameplay mechanics* have you nerds come up with?

**Comment by ike709** [comment]
https://github.com/OracleStation/OracleStation/pull/735 is dead

**Comment by Cactus2388** [comment]
No point in keeping a reskin race that only takes extra damage, I say trash em.

**Comment by The-Driker** [comment]
5: Inability to use guns because dog hands

6: If they do get guns, they have to be Megaman style blasters that shoot bright or neon colored balls of slow moving projectiles, because Ethari don't know how to gun.

**Comment by FlattestGuitar** [comment]
I hate to say it, but this PR isn't really fostering any conversation that we expected to happen here. As such, I don't see the point. 

Let's keep talking about it until we come up with a solution. 

Closing for the time being.

**Comment by ike709** [comment]
image
image
🤔

**Pull request closed without merging**
