### PR TITLE
When there's something rude in your neighborhood

### LINKED ISSUE #810: SSD people killed by revenant (Oversight?)
Be revenant
See person lying on ground
give succ
realize they're SSD
oh shit can't stop succ
kill an SSD

### PR DESCRIPTION
**Pull request by DaveTheHeadcrab**
:cl:
fix: Revenants may no longer employ THE SUCC TECHNIQUE on SSD people.
/:cl:

Fixes #810

Mostly because someone said we couldn't fix this.
Fuck you I fix what I want.

### CODE REVIEW

**Comment by DaveTheHeadcrab** [comment]
I didn't realize it was a Jontron meme I swear please don't hit me

**Comment by Cactus2388** [comment]
papa bless

**Comment by SamHPurp** [comment]
Is this not going to stop you from SUCCing from dead guys who have ghosted?

**Comment by DaveTheHeadcrab** [comment]
@SamHPurp No, because they have no key.

**Pull request merged**
