### PR TITLE
Map edits to make it more Oracle Efficient, Unique and Immersive

### PR DESCRIPTION
**Pull request by LYNXEMS**
:cl: LYNXEMS
   tweak: Created a Blueshield Office where the Janitorial Closet was, a good place to keep track of heads. He even gets a pet that never got much love due to it only appearing in one map.
   tweak: Moved the Janitorial Closet where the IAA office used to be, granting it more space, and it makes sense to be by the Crew Quarters rather than Bridge.
   tweak: Moved the IAA office into the Showcase Room, merging them together into a place of Nanotrasen glory and upholding of bot Space Law and SoP, making the place less redundant and up for placing tesla engines and into something with a purpose and look. Makes sense considering IAA's access and closeness to command staff.
   /:cl:

Maps tested and should work.
-APCs present
-Air Alarms, scrubbers and Vents present
-Fire Alarms and Firelocks Present
-Correct Access Chosen
-MULEBots find their way
-APCs working and light too
-No changes to other files, unused Blueshield area in code used
-Map has been shrunk down a tad, making it load a sliver of time faster.
-All Mapmerged and ready to be tested / roll.

Files changed : MetaStation.dmm

~LYNXEMS

Ideas by the wonderful people up on our discord's #design-ponderings and me, maybe something will make it in.
janiig
bridgeig2
bridgeig1
newjani
bridge
tide
iaaig

### CODE REVIEW

**Comment by LYNXEMS** [comment]
I ought to add pictures. 

Janitorial Closet

janitor

Blueshield's Office

blueshield

IAA Office merged with the showcase room

iaa

Changes can always be done if requested.
The Beerkeg Nuke has been moved into Bar Maintenance, here

barmaint

~LYNXEMS

**Comment by AdamElTablawy** [comment]
IAA office looks like shit

you removed the bridge's plastic-flap weakness for no reason in moving blueshield office

**Comment by LYNXEMS** [comment]
Mhm, I understand the complaints and negative feedback, but should the Blueshield get an office, and would the gateway room be good for it? It makes no real sense for him to only get a locker slapped in a meeting room.

**Comment by CorvetBlyat** [comment]
I really want this PR to go through, Blueshield getting an office would be great in my opinion.
However, The janitorial closet and Blueshield office seems kinda empty and clunky, however if that was refined i would be all for merging this. In my opinion the gateway room is too big for the office and should be kept for something else that may come up.

**Comment by LYNXEMS** [comment]
Changes can always be done, preferably given an idea.

**Comment by AffectedArc07** [comment]
If this gets merged, ping me so I can make webmap updates

**Comment by FlattestGuitar** [comment]
I don't see the point in adding a Blueshield's office, they don't do anything at all that would require one. Plus, I'm actually considering removing the job outright, since it's mostly useless.

The IAA office is *alright*, but there can definitely be improvement. The big-ass glass cases in the corners really should go, they shouldn't be hidden behind consoles in the office, that makes no sense. Also, you're inconsistent with how you apply the glass panes in the corners.

The janitor's office seems far too spacious and awkward. Needs to be smaller or more populated with potted plants or something.

**Comment by FlattestGuitar** [comment]
I like the IAA office.

I think the Blueshield and Janitor office changes are pointless, though visually they look nice now.

**Comment by SamHPurp** [comment]
Conceptually I think the blueshield getting a proper office is a waste of time and space.

**Comment by LYNXEMS** [comment]
Conceptually, Maybe, but it's more of a fluff addition, and something to make the role seem more real and to make that place better, because the Janitorial closet shouldn't be by all the command facilities.

**Comment by Cactus2388** [comment]
My notes:
- Nuke beer keg is in the way, and is obviously there JUST to keep it in commission. Move it or remove it (captain's bedroom?)
- IAA office is in a nice place, don't mind the Janitor's office 
- IAA office lacks a cabinet with the Nanotrasen contracts and breaks the Devil gamemode
- Blueshield office is in an ok place
- Blueshield office doesn't need a Space Law book, they're not a part of law enforcement
- The protection of the bridge is buffed (while not necessarily a bad thing) because of the plastic flaps AND command airlock
- Blueshield's office is very bland and flavorless 
- Blueshield's office is just pretty ugly in general

**Comment by LYNXEMS** [comment]
IAA

iaa3

Cap
cappy

Blueshield

blueshit3

Changed all requested things, still fighting to get this PR merged

The bridge is bland and flavorless fully, Blueshield is made to fit in with their style, just need to look at all of them.

**Comment by Ralta** [comment]
Irrespective of the Blueshield's changes, I actually love the idea of this PR. The ja it or  a proper office close to dorms is nice, and the IAA being more centralised in an NT-centric place is awesome.

I agree there could be some changes to layout n such, but the core concept is good. As for the Blueshield's office, I'm pretty ambivalent about it. I don't think a Blueshield should ever really spend time in an office if they have one, which makes it kinda redundant. That said, I'm not sure what to suggest otherwise.

**Comment by SmokingKilz** [comment]
I am heavily against the idea of remove don't improve and would be against the Blueshield being outright removed without us trying to improve the role. I like the PR as a whole, however one of the points raised is pretty important which removes the flaps from the bridge. I'll also agree that the Blueshield's office needs some changes, the consoles aren't in the best of place. Now, I think an office makes sense, it gives them a place to spawn and store their items without it just being a random locker tucked away somewhere on bridge.

Also is gives them a good central place to monitor heads via the monitors. A good Blueshield doesn't always want to be shadowing a head anyway, they're most useful in a central position on the station to be as close as to all heads at a given time. Not to mention we want more roleplay and it offers them a good place to roleplay. 

I'm all for this, I like the changes for the most part and see barely any cons and more pro's.

**Comment by FreeStylaLT** [comment]
I suggest updating your OP with the most recent pics.

Also including an in-game shot w/o all that cables and markers / effects can also help people see how it'll actually look like.

As for the actual changes, there are some minor issues with flow and such that I noticed:

- The BS office seems to have an inconvenient / impractical turn when trying to get to it
img
If you were to move the office to the right or somehow lower the office to make the line from bridge to the office straight / only have one turn, you could fix the impractical flow.'

Another thing about the BS office:
img
Although this is a convenient shortcut into Bridge, it seems that if there's anyone in the office, especially if sitting in front of the table, they'd get pushed / swapped as someone goes through. You also don't seem to have a space for a stool / chair for visitors.

Beyond that, I'd also move the ID swiper to somewhere other than the corner that's only accessible by standing in that previous straight line, the BS could get swapped by anyone passing by. Somewhere in the northern part of the office, around, or on the table, maybe? 

You could also move the office chair one tile left and then move the console to the right of the chair, for maximum cramping points.

- As for the Janitor closet:
It seems to have a boxy feel to it, I would suggest giving it an irregular shape, kind of like this:
img
Cutting corners (heh) usually results in a more interesting-looking design.

- IAA:

I would say the oddest thing about the IAA office is that all the conversations the IAA has would be heard by anyone else in the waiting room, also the only interaction the crew can have with them is across a windoor'd table as if they're some sort of bureaucratic complaint handl... huh.

Overall, these are neat changes, though I have to wonder about BS's office placement.

**Comment by SmokingKilz** [comment]
Also shutters on all windows and restricted door access on the IAA office is almost a must have in my opinion.

**Comment by FreeStylaLT** [comment]
Also, I'm 90% sure you didn't mapmerge the file if it has 25k changed lines despite you changing ~3 rooms

**Comment by FlattestGuitar** [comment]
Free has a point. That won't get merged without a proper mapmerge being done.

**Comment by LYNXEMS** [comment]
Changes will be done today, blue door is access locked. Shown cons will be fixed

**Comment by LYNXEMS** [comment]
Okay, here goes.

IAA remains mostly unchanged, added shutters as it was asked
In-game
iaaig

Janitor was given the asked interesting look
In-game
janiig
Behind Scenes
newjani

And here goes the bridge
-I had to add three tiles to captains and blueshield office to resolve the odd curve, and make it symmetrical. They were filled with things not to look empty
-Blueshield office layout changed slightly - Heads can now sit together and discuss their security!
-Bridge was given a vulnerability with the flaps, delivery works. It was put in a good place in my opinion. Only one table and machine was moved, and an unreachable empty bookshelf deleted. MULEbots work and find their way
-Nuke moved into a secret-like place similar to the captain secret.

I couldn't find an another way, brainstorming took me more than 4 hours

In-game
bridgeig1
bridgeig2

Behind scenes
bridge

-I have remapmerged everything from the base Metastation on main branch, did it good and surely.

**Comment by SamHPurp** [comment]
Yes, you still haven't map merged...

But I still think I disagree with all of these changes. I don't see the value in them, and some are objectively worse.

**Comment by LYNXEMS** [comment]
> I recommend backing up your map file, resetting this branch to master, preparing mapmerge, then copy pasting your changes onto the fresh map file, running mapmerge and forcing a commit to fix the merge issue.

I swear I did that, maybe it was the fact that it had to clean the dictionary, as mapmerge said

> But I still think I disagree with all of these changes. I don't see the value in them, and some are objectively worse.

Still looking for ways to improve, because there really are issues there now, and I think while I might create some small issues, they outweigh the current lacks and problems...

**Comment by SmokingKilz** [comment]
I actually like the changes, I see no con's but some some subjective ones. I support this.

That being said as I stated before the map merge issue has to be fixed before this can go anywhere.

**Comment by SamHPurp** [comment]
We're not going to codify BS further in, and 99% of the changes are a result of your attempt to place a BS office where it is.

The BS having an office is not a positive addition to the role, and will not promote the type of behaviours we want.

This also removes a close location to the bridge for nefarious deeds.

This also adds an additional escape/attack path for the bridge.

This moves the IAA far away from security.

Ultimately, this isn't going to go in, for these, and other reasons expressed above.

**Pull request closed without merging**
