### PR TITLE
Makes ID sprites less garbage

### PR DESCRIPTION
**Pull request by FlattestGuitar**
The Bay sprites are just fuckin' ugly. I remade all of them to fit the tg style with sharper edges and more crisp colors. There aren't a lot of significant differences, but these look way better than what Affected just ported.

This also takes out the ones that aren't used at all because for whatever reason the last PR was merged with a lot of redundant sprites.

The lifetime and rainbow sprites took way too long to make before I realized they're unused, so they're going to be used at some point because I say so.

ADDS AN ADMIN ID - BECAUSE FLATTEST ADDS UNDOCUMENTED THINGS LIKE A JERK

### CODE REVIEW

**Comment by AffectedArc07** [comment]
I was about to make this PR until I saw the embed in discord

**Comment by SamHPurp** [comment]
`This also takes out the ones that aren't used at all because for whatever reason the last PR was merged with a lot of redundant sprites.`

Not liking that my dudes, but glad it fixed.

**Comment by SamHPurp** [comment]
Also I'm assuming the other PR since it was an AA port, it didn't add repainting of IDs? Should get that done too at some point.

**Comment by SamHPurp** [comment]
Also.... undocumented changes reeeeeeeeeeeeeeeeeeee - adds an admin ID.

**Pull request merged**
