### PR TITLE
Food cart changes

### PR DESCRIPTION
**Pull request by Quantum-M**
Updates the kitchen's icecream vat cart and the food cart.

:cl: 
tweak: Updates kitchen icecream vat cart and food cart
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Umbrella removal is a crime and I do not condone this.

**Comment by Quantum-M** [comment]
The umbrella was a abomination, and it doesn't rain inside the station.

**Comment by SamHPurp** [comment]
I do miss the large wheels tbh.

**Comment by Quantum-M** [comment]
Food cart gets it's big wheel back, ice cream cart is untouched.

**Pull request merged**
