### PR TITLE
Clowns as a Species (CaaS)

### PR DESCRIPTION
**Pull request by AndrewMontagne**
Adds clowns as a roundstart, playable race! You can even customise the appearance of your clown!

image

Comes complete with transformation disease: ***The Honkening***

gif

Still not finished, but didn't want to wait for another good issue numberwang to use.

:cl: AndrewMontagne
add: Adds clowns as a roundstart race.
/:cl:

### CODE REVIEW

**Comment by Ralta** [comment]
+1, test merge now pls and thanks.

Srsly though, gonna work on some lore for this (already discussed some ideas with Andrew) and having tried it out, it's hella-fun.

**Comment by FlattestGuitar** [comment]
no

**Comment by ike709** [comment]
*This* is what you've been working on?

**Comment by Ziiro** [comment]
not a meme pr

speedmerge

**Comment by SmokingKilz** [comment]
Yeah okay, lets just speedmerge this please. On a serious note, clowns are already their own species, viva la clown planet.

**Comment by SamHPurp** [comment]
With us making Etharis the only race, we'll be closing this PR.

**Pull request closed without merging**
