### PR TITLE
Better windows

### PR DESCRIPTION
**Pull request by AffectedArc07**
Changes the windows from the fulltile to the "para style" ones which are singular "thin" windows.

Before:
image

After:
image

:cl: AffectedArc07
tweak: Windows are now the paned versions instead of fulltiled
/:cl:

**TO THE PEOPLE WHO ARE GONNA COMPLAIN ABOUT MY COMMITS**
When all my open PRs are closed or merged, I will fix this. I know what to do now, and how to update without excess commits.

### CODE REVIEW

**Comment by SamHPurp** [comment]
Uh, by better do you mean, entirely worse in every way?

**Comment by AffectedArc07** [comment]
How are they worse?

**Comment by Cactus2388** [comment]
I like these

**Comment by SmokingKilz** [comment]
But we already have that kind of window style?

**Comment by DaveTheHeadcrab** [comment]
Objectively worse.

**Comment by Fox-McCloud** [comment]
Just a quick comment. These are better from a design perspective; they have one major thing going for them; they communicate how much damage they've taken--single pane windows don't do that (and it would be hard to communicate on such a tiny sprite).

While it's a bit subjective, aesthetically, having windows that smooth together into a logical unit is generally going to look more pleasing and professional than just abruptly broken panes of glass.

**Comment by SamHPurp** [comment]
Sorry AA, this is overwhelmingly not supported.

**Pull request closed without merging**
