### PR TITLE
ID Card Icon Changes

### PR DESCRIPTION
**Pull request by DaveTheHeadcrab**
:cl:
imageadd: ID card icons have been changed to a new set.
/:cl:

[why]:
I think these ID cards are an improvement over the current version, they look pretty spiffy!

The base set of icons was made by a user on our discord who left these for us to use, then quit the discord. I expanded the set for every ID card in our cards.dmi folder.

id-cards

In the order they are seen above:
base icon, civilian id, data card, old civilian id, old security id, old science id, old engineering id,
prisoner id, captain's id, hop's id, fingerprint cards and hack o' lantern (unchanged), ce id,
cmo id, rd id, hos id, ert base id, ert engineer id, ert janitor id, ert commander id,
ert medic id, ert security id, admin id, medical id, security id, cargo id, engineering id,
research id, mime id, clown id, centcomm id, syndicate id, syndicate commander id, deathsquad id,
emag, blueshield id, rainbow id, "lifetime" id

### CODE REVIEW

**Comment by SmokingKilz** [comment]
Assuming the rainbow colored one is suppsoed to be the emag. I'll say that all of those look really neat apart from the emag, I'd like to keep our current one.

**Comment by ike709** [comment]
@SmokingKilz no you fleeb the emag is the bottom left icon

**Comment by oversane** [comment]
tweaked that emag because i dont know
also tweaked your nuke op card a bit too
syndie op
emag

**Comment by Xantholne** [comment]
Look pretty good, I'd approve of.

Personally though I'd prefer if the old ones were marked as their current but with OLD at the end so they aren't lost.

**Comment by FlattestGuitar** [comment]
I don't have strong feelings about these, but they seem a bit too cartoony to me. 

Also, the emag sprites suck butt. All of them.

**Comment by SamHPurp** [comment]
Hmm. I think I like it.

The Emag however isn't obvious enough at all though.

**Comment by AffectedArc07** [comment]
What @FlattestGuitar is trying to say is that he spent too much time on the current ones and doesnt want that to go to waste (mainly lifetime and rainbow, even though they arent used)

**Comment by DaveTheHeadcrab** [comment]
So if I reverted the emag to the previous icon would this get merged?

**Comment by AffectedArc07** [comment]
Side note, we still need the code that allows you to change card color with the ID machine

**Comment by SmokingKilz** [comment]
I personally think the only issue is the emag, thumbs up from me so long the emag one is changed to what it is currently.

**Comment by SamHPurp** [comment]
@DaveTheHeadcrab Yes, imo - revert emag if you can't come up with a better one... and it'll be okay to merge.

**Comment by DaveTheHeadcrab** [comment]
@SamHPurp Sorry for the delay, emag reverted to the previous icon. 'New' emag icon kept in the file as emag_alt in the event we want to switch or modify that at a later date.

**Comment by SamHPurp** [comment]
We might roll this back. Lets try it for a bit and get feedback!

**Pull request merged**
