### PR TITLE
Adds a cryostorage room to Pubbystation

### PR DESCRIPTION
**Pull request by Quantum-M**
Adds a cryostorage room to pubbystation, its at the entrance of dorms, above cargo.

:cl: Cryopods to pubbystation
add:  Adds Cryopods to pubbystation
/:cl:

Tested
cryo

### CODE REVIEW

**Comment by SamHPurp** [comment]
Give it its own APC, also need a camera.

**Comment by Quantum-M** [comment]
APC and camera added.

**Comment by SamHPurp** [comment]
Looks like you've mapped the area as medical/cryo - this isn't the right one for cryo.

Check one of the other maps, I forget what its called, but it isn't listed under Medical I'm almost certain.

**Comment by Quantum-M** [comment]
The one in metastation listed it as that, although I may had confused it.

**Comment by Quantum-M** [comment]
Metastation cryo list its area as /area/medical/cryo

**Pull request merged**
