### PR TITLE
Kill yourself nerds...

### PR DESCRIPTION
**Pull request by SamHPurp**
... Physically. No just typing Suicide anymore.

:cl: Purpose2
del: Removes the suicide verb. You'll need to actually just kill yourself, or ghost.
/:cl:

Disclaimer: Don't actually kill yourself.

### CODE REVIEW

**Comment by Ziiro** [comment]
Throwing my opinion out there: Strong disagree.

As per our discussion in discord that actually reminded you to do this PR: There's a lot of hilarious and great suicide verbs in the code with things you can't actually kill yourself with.

Suicide already requires free hands - you can't do it while cuffed. If you throw a prisoner into perma and they have nothing to actually kill themselves with, it might be tedious.

Additionally, if they suicide without using the suicide verb, people are likely to waste time trying to revive them.

**Comment by Xantholne** [comment]
fuck your disclamer

**Comment by SamHPurp** [comment]
>it might be tedious.

Ghost, yo. This lets people just cryo you and open the job slot.

Suicide should be impactful. Currently its more like "oh we got another suicider lols"

**Comment by FlattestGuitar** [comment]
I'm not sure about this.

We should carefully examine all the situations in which people reasonably use the verb and see whether this PR offers an improvement over the current system.

Caught by Sec and want to go play Lifeweb instead? Now Sec won't know what to do with an SSD body.

**Comment by Ziiro** [comment]
Could you move the suicide_act to harm intenting yourself in the mouth(or head) with certain items to cause the special verb? I just feel like it's a net loss to get rid of those, at least.

**Comment by SamHPurp** [comment]
>Caught by Sec and want to go play Lifeweb instead? Now Sec won't know what to do with an SSD body.

Ghost.

> I just feel like it's a net loss to get rid of those, at least.

There were some fun jokes in there, but its ultimately tired memes.

**Comment by Joseph-Case** [comment]
But I like the ability of suiciding with a volumetric air pump and blowing my brains out

**Comment by EldritchSigma** [comment]
Remove Greentext so sec cant be so fucking hungry for their valids when they meta your "Die." objective and I am all down for this thing. Heck remove greentext altogether since it brings out only the worst of people... that worst aspect is competitiveness.

**Comment by EldritchSigma** [comment]
Atleast add the weakass suicide implant with a limit of one per traitor so traitors can waste TC on being able to suicide on command... so sec doesnt get their fucking valids.

**Comment by SavinienBrassheart** [comment]
I honestly cannot see the benefits outweighing negatives here. While most may use suicide as a way to get out of perma prison, at the same time I have also seen it used as a powerful RP tool. From an officer strangling himself in grief over failing to save a loved one from being burnt alive by an evil chaplain, to a captain sitting in his office apologizing to his crew as self-destruct timer ticks down and xenos claw at his doors before blowing his own brain out. Moments like that would lose something, if say the captain just had to sit there and spam shoot at himself and then fall into crit and slowly die. Or if that officer had just ghosted.

And as others have mentioned it is easier and more instinctive for most to know what to do with a suicide, over someone who just ghosted. All in all, I just don't believe this is a good idea.

**Comment by EldritchSigma** [comment]
Alright I thought about it... once theres genpop for prison, that means only ultra hard crimes like killing someone can result in perma (but mostly results in execution) I dont mind this at all. Aslong there are tools in perma to kill yourself with and no shitcurity interferring I dont mind this whatsoever. Alot of the suicide verbs are shitty memes (just look at the nuke disk one).

**Comment by DaveTheHeadcrab** [comment]
I agree with Andrew. The current suicide verb is pretty cartoonish and I dislike it. If you're going to commit suicide in-game there are plenty of other ways to do it.

**Comment by Cid777** [comment]
> We should carefully examine all the situations in which people reasonably use the verb and see whether this PR offers an improvement over the current system.

Literally what situations? In whatever situation you're imagining, where suicide would be reasonable, they would have access to a less RP damaging method.

> Caught by Sec and want to go play Lifeweb instead? Now Sec won't know what to do with an SSD body.

Is this really a significant problem? Security is inconvenienced for a moment?
If they were already in the brig, or being arrested when they went SSD, Security can keep them there.

> From an officer strangling himself in grief

This could be seen as _bad_ for roleplay, choking yourself to death is probably pretty difficult, even out of grief. 

> a captain sitting in his office apologizing to his crew as self-destruct timer ticks down and xenos claw at his doors before blowing his own brain out.

This is still possible, unless TG handles suicide with a gun in a different way to Para.

> Moments like that would lose something, if say the captain just had to sit there and spam shoot at himself and then fall into crit and slowly die.

That's more a problem with how shooting yourself is handled, than anything. That can be fixed.

**Comment by imsxz** [comment]
Im against this pull request, but I can't think of any worthwhile reasons to keep the verb. Lots of the suicides, while sometimes entertaining, are usually just silly and unrealistic.

Off the top of my head, I can't think of any time I've used the suicide verb where ghosting wouldn't have been acceptable.

The argument could be made that watching a perma prisoner suicide in some silly way would make more sense then them randomly going braindead/catatonic bia ghosting. That's all I got, though.

**Comment by FlattestGuitar** [comment]
I'd merge this tbh.

**Comment by SamHPurp** [comment]
Good to merge then @FlattestGuitar - @AndrewMontagne had already approved it, but my conflict fixing auto-dismissed it.

**Comment by SmokingKilz** [comment]
I know it's about to get merged, but does this actually change the ability to commit suicide by harm intenting your mouth with a gun? I'm not sure if TG had something like that to begin with, but mechanical ways to commit suicide will make a lot more sense from an RP standpoint instead of bashing your head in with an O2 tank.

**Comment by Ziiro** [comment]
That's not under a `suicide_act`. It's actually right here, and isn't being touched by this PR: https://github.com/OracleStation/OracleStation/blob/f81f7e8612aac003163343fb56888649d5fc45b3/code/modules/projectiles/gun.dm#L375-L382

**Comment by AndrewMontagne** [comment]
Merged this, taking Flattests earlier comment as an implicit approval.

**Comment by SavinienBrassheart** [comment]
Yeah I will admit reading all the comments and such, I have actually softened my stance and can actually see this being very beneficial.

**Pull request merged**
