### PR TITLE
Updates the cloner sprite

### PR DESCRIPTION
**Pull request by Quantum-M**
Updates the four cloning sprites.

:cl: 
tweak: Updates the cloning sprites
/:cl:

UPDATE: More work done to the cloner sprites.

cloningmn
clonermc
cloningmb
cloningmm

### CODE REVIEW

**Comment by SmokingKilz** [comment]
Neat-o

**Comment by SamHPurp** [comment]
It seems like its gotten so much flatter, lost a lot of depth in your rework...

**Comment by Quantum-M** [comment]
@SamHPurp I'll work on it, but can you point out what areas seem to make it look more flat? I am very sure its the dome and glass areas in my opinion.

**Comment by Quantum-M** [comment]
Sorry for taking some time in getting back to this.
clonertwo

I am still figuring out the glass, but thoughts, @SamHPurp ?

**Comment by Quantum-M** [comment]
Closing this for #1076. Going to save the sprites and think of a improvement.

**Pull request closed without merging**
