### PR TITLE
Lavaland tweaks!

### PR DESCRIPTION
**Pull request by FlattestGuitar**
:cl: Flatty
tweak: Tweaked all the lavaland creatures to be easier to fight against on our lower movespeed
/:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
How about you make megafauna optimised for this move speed since you removed scooters like a meanie

**Comment by Cactus2388** [comment]
Goliaths, watchers, and legion aren't the issue it's the literally unbeatable fauna people have a problem with.

**Comment by Ziiro** [comment]
the other codebases are going to laugh at us for this one

**Comment by Ziiro** [comment]
the other codebases are going to laugh at us for this one

**Comment by SamHPurp** [comment]
Time to get good

**Comment by SamHPurp** [comment]
I've been asked to explain further.

The fact that our Lavaland is harder than TG is a feature.

I would support some minor minor minor tweaks to Hiero & Collossus, but not as wide-reaching as all these changes.

**Pull request closed without merging**
