### PR TITLE
Expands IAA office in metastation

### PR DESCRIPTION
**Pull request by Quantum-M**
Expands the IAA office into the front courtyard it has. Redirects the entrance of dorms. Makes the side tool storage smaller.

:cl: 
tweak: Expands IAA office, redirects path to dorms, side tool storage made smaller.
/:cl:

Reasoning is that the current IAA office is rather small for two IAAs and is a bit isolated from public areas. There has also been previous arguments about the IAA office needing to stay near Security and the courtoom. With these changes, the IAA office stays in its same spot, but its bigger and has a more direct view to public areas (Central hallway).

iaanewone
iaaofficetwo
iaaofficethree
iaaofficefour

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Something we agreed on the PR review meeting. The rest of the nitpicking coming from Purpose.

**Comment by Quantum-M** [comment]
@FlattestGuitar @SamHPurp addressed: 
iaanewone

**Comment by Keluandrie** [comment]
That's a big yes from me.

**Comment by Quantum-M** [comment]
I think conflicts should be fixed now.

**Pull request merged**
