### PR TITLE
Removes the build your own shuttle kit

### PR DESCRIPTION
**Pull request by AffectedArc07**
I am pretty sure EVERYONE by now is fed up with the same thing happening each round. All the BYOSK does it piss off the entire crew and generate copious amounts of salt, honestly the asteroid is better than this. Yes I know this is a salt PR but I feel it is required, since I think EVERYONE can agree the BYOSK is a pain in the ass for everyone involved, including just general crew

:cl: AffectedArc07
del: Decomissioned the Build-Your-Own-Shuttle-Kit. We apologise for any happy emotions this may cause.
/:cl:

Why: Fed up with the hell each round.

### CODE REVIEW

**Comment by SamHPurp** [comment]
fyi your PR will do nothing when merged. We'll need to manually edit this server-side if we do wish to 'merge' it.

**Comment by AffectedArc07** [comment]
I was gonna add config change in the title

**Comment by Iamgoofball** [comment]
try building a shuttle

**Comment by Keluandrie** [comment]
@iamgoofball what tends to happen is that people start building, antags happen or people get distracted, and a halfass shuttle is what's left. I personally think it shouldn't be removed, it's unfortunate when it happens but it still has lots of potential. Maybe have the DIY shuttle spawn with some drone shells that ghosts can use to build.

**Comment by AdamElTablawy** [comment]
it's good for blob rounds though

in fact it's the only reason oracle has ever beaten a blob that even mildly knows what it's doing because free cargo points

**Comment by Rumiluntti** [comment]
It's literally the one shitty captain that has that shuttle as his autism obsession.
I believe the problem can be handled with administrative actions

**Comment by FlattestGuitar** [comment]
Fuck it we'll tweak the live server when we get around to it or sth

**Pull request merged**
