### PR TITLE
Atmos sprites improvements.

### PR DESCRIPTION
**Pull request by AndrewMontagne**
image
image image

Canister sprites are by me! Slowly getting the hang of spriting shit. Air pump and space heater sprites modified to fit into 3/4 perspective.

:cl: AndrewMontagne
imageadd: Added new canister sprites.
imageadd: Changed air pump sprites.
imageadd: Changed space heater sprites.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
I think they're a bit too tall. I'd squash them a bit.

Also, I think making the middle bit a bit darker might help how they look. They seem a tad too shiny to me.

**Comment by AndrewMontagne** [comment]
They're metal canisters. They're supposed to be somewhat shiny. 🤔

**Comment by Ziiro** [comment]
Is it out of the question to have some sort of default signage on them somewhere with what's in them? 🤔

**Comment by Joseph-Case** [comment]
@Ziiro the only cannister with signage by default is plasma, so.... (shrug)

**Comment by FlattestGuitar** [comment]
I like the air pump; dislike the cannisters. They're overly uniform, shiny and gigantic. 

The code works fine otherwise.

**Comment by SamHPurp** [comment]
I like the direction. I think these could be tightened up a bit in future, but 👌 for now!

**Pull request merged**
