### PR TITLE
Secborgs become available if security is understaffed

### PR DESCRIPTION
**Pull request by Ziiro**
:cl: 
add: If there are 0 active, or only 1 active security officer, secborg module can be picked by borgs.
balance: Secborg stunbaton replaced with classic baton
tweak: Made the `do_transform_animation` wording more relevant to Oracle
/:cl:

[why]: Security is often understaffed, or completely outplayed when it comes to antagonists. I'd like to throw them a bone. These borgs do not have hybrid tasers, but a disabler instead. And I have replaced their stunbatons with wooden batons.

dreamseeker_2018-02-13_11-17-20
dreamseeker_2018-02-13_12-19-58

### CODE REVIEW

**Comment by ike709** [comment]
Honestly I'd say as long as there is 3 or less sec officers borgs should be able to go sec.

**Comment by SamHPurp** [comment]
🤢

**Comment by ike709** [comment]
"I'd rather real crew" isn't a valid option when nobody plays security officer.

**Comment by Xantholne** [comment]
Zero to at max maybe 3? Depending on population; Security officers would be fine.

As it stands most will argue that Secborgs aren't much of a solution but it does provide another means to increase Security as we are super, super lacking. Somedays we have 1, maybe 2 officers, maybe on a blue fucking moon: followed by some 6-7 antags. On occasion we've had 0 Officers but just a brig physician and 7 antags. A change to encourage some other means of acquiring Security is much needed.

**Comment by SamHPurp** [comment]
I am still against this. However with Flattest merging #625 - perhaps the problem this PR is attempting to address will be resolved.

**Comment by Ziiro** [comment]
This needs to be reopened. Even with the prioritization, we're getting security that is being chewed up and spat out pretty constantly. Additionally, we're still generally understaffed and greytide is out of control, making for a pretty miserable game experience.

**Comment by davethwave** [comment]
Just make it so that only certain people can be sec borgs depending on ban history and so forth.

**Comment by SamHPurp** [comment]
Everytime I've been on lately, Sec was full.

**Comment by Ziiro** [comment]
Okay, but how many hours have you been on in the last week? Multiple shifts in a row, multiple times of day, the greytide is out of control and security is undermanned or not responding to calls. Full stop. That's my experience, day after day. 

It's **extremely hard** to tell players that self antag and get into fights "You are not to kill people or hunt antagonists,, let security stop them" when security doesn't exist or respond.

**Comment by davethwave** [comment]
Besides the Secborgs have the condition in this case of if there isn't enough sec on station so you will only see the secborgs if at all if there are not enough sec on board.

**Pull request closed without merging**
