### PR TITLE
Messenger Bags

### PR DESCRIPTION
**Pull request by FlattestGuitar**
Ports Messenger bags from Bay.

You can pick those as an alternative to backpacks, satchels and duffels in the character setup menu.
They do not differ from the backpack in terms of functionality, pure fluff.

:cl: Flatty
add: Adds messenger bags! Pick those as an alternative to your backpack in the character setup menu.
/:cl:

### CODE REVIEW

**Comment by Ralta** [comment]
Oo, these like nice. Want!

**Comment by Ziiro** [comment]
Wait, so these cause the same slowdown as backpacks? They aren't like stachels?

**Comment by Cactus2388** [comment]
> They do not differ from the backpack in terms of functionality, pure fluff.

@Ziiro

**Comment by ike709** [comment]
They should be a middle ground between satchels and backpacks in terms of slowdown and capacity imo.

**Pull request merged**
