### PR TITLE
Adds a new admin fun verb

### PR DESCRIPTION
**Pull request by AffectedArc07**
This PR will grant admins the ability to play a meme that is probably going to die within a month. 

Reasons this probably wont get merged:
- Copyright is a thing
- Its a meme PR
- Its a shitty meme PR at this

:cl:
add: despacito
soundadd: despacito
/:cl:

Why: I have no idea what I am doing with my life, and flattest said I could submit this due to being a meme

### CODE REVIEW

**Comment by AffectedArc07** [comment]
I blame flattest

**Comment by Cactus2388** [comment]
shitty meme

**Comment by Ziiro** [comment]
i'm sure your reddit post about this will get you upvotes

**Comment by AndrewMontagne** [comment]
No.

**Pull request closed without merging**
