### PR TITLE
Medbot faces!

### PR DESCRIPTION
**Pull request by FlattestGuitar**
Took me way longer than it should have. The colors aren't in place yet and I have to test all this, so DNM.

They have special expressions for a handful of different events, but I won't ruin that for you. The gif is purely idle emotions, which they do on..being idle.

:cl: Flatty
add: Your medbots might wink at you. Watch out.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
You'll note the icons don't actually play the animations properly and cut them randomly. I consider this a feature, because they seem even more lifelike. I'm tearing up as I say this.

**Comment by Quantum-M** [comment]
If a medibot winks at me, would I be able to take it to the IAA for harassment?

In seriousness, is it possible to give it a talking icon when it says stuff?

**Comment by Cactus2388** [comment]
The yellow is really ugly

**Comment by AdamElTablawy** [comment]
haha wow! this is hideous

**Comment by FlattestGuitar** [comment]
That hurt my feelings. :c

**Comment by AdamElTablawy** [comment]
these hurt my eyes

**Comment by spoonitate** [comment]
While Adam was being pretty rude about it I do agree that the color is a bit offputting. Maybe turn it a shade of green like what I showed you a while back?

**Comment by Rumiluntti** [comment]
Ebin smileycentral medibots.
Please no

**Comment by Cactus2388** [comment]
Medibots are autonomous and don't need emotions. The piss yellow is off putting and doesn't match with anything else we have either.

**Comment by miniusAreas** [comment]
this is great, yes.

**Comment by FlattestGuitar** [comment]
I give up. Nobody likes my art. I'll commit a genocide instead. ;c

**Pull request closed without merging**
