### PR TITLE
Tg station ports v5

### PR DESCRIPTION
**Pull request by scrubmcnoob**
ports:
tgstation/tgstation#31236
tgstation/tgstation#31181
tgstation/tgstation#31208
tgstation/tgstation#30998
tgstation/tgstation#31261
tgstation/tgstation#31260
tgstation/tgstation#30885
tgstation/tgstation#31256
tgstation/tgstation#31180
tgstation/tgstation#31238
tgstation/tgstation#31150
tgstation/tgstation#31283
tgstation/tgstation#31281
tgstation/tgstation#31287

porting and 3AM aren't good combos.

### CODE REVIEW

**Comment by SamHPurp** [comment]
31208 looks incomplete - I don't think you finished porting it?

**Comment by SamHPurp** [comment]
also yuck b61a6b5 then being reverted by 51f4fb6

**Comment by SamHPurp** [comment]
lol and 7521d7a getting reverted by 2f3d1b5 which also is then re-reverted by dee3fe6

**Comment by FlattestGuitar** [comment]
If this bugs out I will stab a baby.

**Pull request merged**
