### PR TITLE
Adds new HUD Glasses Sprites

### PR DESCRIPTION
**Pull request by Xantholne**
New sprites for Medical HUD, Security HUD, Security Sunglasses, Diagnostic HUD, and their Nightvision equivalents.
d06390999e4a3abccf610e8823231b25
aabcef7c25be84c9aa1f49f8d0d9e846
3acccc2d970541fa8cd85ab64ee74122
 Updated to cleaned up versions. Now more slim

:cl: Xantholne
add: New Sprites for Med Hud, Sec Hud, Sec Sunglasses, Diagnostic Hud, and their NV versions.
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
Those are fucking enourmous 👎

**Comment by Xantholne** [comment]
Yeah I'm gonna redo them later. Totally not because @FlattestGuitar is a bully or anything.

**Comment by Joseph-Case** [comment]
I don’t know it I like the sprites for the item, the head sprites are good though

**Comment by Xantholne** [comment]
@FlattestGuitar plz review I think it's done now unless you still feel disgusted by my object icons

**Comment by FlattestGuitar** [comment]
I hate to say it, but I also don't like these. They are just not an improvement over what we had before. The white lines in the middle look like some curly bits of whipped cream and the whole thing resembles a Cylon Raider fighter more than a HUD.

**Comment by SamHPurp** [comment]
Afraid I agree with @FlattestGuitar These sprites are better than your old ones, but still worse than the existing, largely for the reasons stated above.

**Comment by Xantholne** [comment]
Well can you be more specific about what you don't like?

Like is it the object icons? The mob icons? What about them on either?

**Comment by imsxz** [comment]
IMO it's too hard to tell if they have flash protection at a glance. Also they just seem a lot more bulky than the current sprites.

**Comment by FlattestGuitar** [comment]
The icons don't do a good job of actually looking like HUDs to someone who doesn't know their function to start with.

There are thick outlines which look inconsistent. 

The white gleamy lines in the middle also don't have a consistent pattern, making it look messy.

The red one has a black outline on the visor, while the pink one doesn't, for whatever reason.

It's impossible to tell which ones have flash protection and which ones don't.

I think the current HUDs and sunglasses just have a nicer design, sprite quality aside.

**Pull request closed without merging**
