### PR TITLE
New Cloner Sprites

### LINKED ISSUE #564: Deconstructing and reconstructing the cryotubes changes the sprite.
image

### PR DESCRIPTION
**Pull request by AndrewMontagne**
Reworked the cloner sprites to be based off the cryotube. Comes complete with disturbing clone growth animations!

Meat mob sprite ported from CEV Eris.

gif gif

Also fixes #564!

:cl: AndrewMontagne
imageadd: Replaced cloner sprites
/:cl:

### CODE REVIEW

**Comment by Quantum-M** [comment]
Clamp part looks a bit odd, I think the edges needs to be lightened up a bit.

**Comment by FlattestGuitar** [comment]
Not a fan of clones starting bald. I love the clone haircut.

**Comment by Partheo** [comment]
The body really should float around in it, I think. It looks very odd simply staying there without moving.

**Comment by AndrewMontagne** [comment]
@Partheo Are you blind? It does move! There's an entire growth animation as well as a bobbing animation!

**Pull request merged**
