### PR TITLE
METASTATION - Removes chaplain soul shard

### PR DESCRIPTION
**Pull request by Quantum-M**
Removes the Chaplain's soul shard from metastation.

:cl: 
del: Removed Chaplain soul shard from meta station
/:cl:

The chaplain soul shard tends to bring several issues, especially if the chaplain is not a antag. The times it has been used, the chaplain has resorted to soul shard people without good reason, and even then, a normal person, RP wise, doesn't have a reason to be killed and become a ghost.

It also encourages the chaplain to validhunt in my opinion, soul sharding any antags if they happen to come across any. It's also a instant body destroying item, once someone gets sharded, they are dead, unable to revive, and end up stuck as a crappy simple mob, and the Chaplain _already_ has the cremator available, it shouldn't be that easy to fully remove someone from the round.

Lastly, the soul shard is primarily seen as a cult item, it makes no sense for a chaplain to have a item that is used by a rival, violent religious cult.

### CODE REVIEW

**Comment by SmokingKilz** [comment]
I mean there's the works of replacing it with something more holy-like. I'd like to see the current soul shard get replaced with that.

**Comment by Quantum-M** [comment]
That would be a alternative to this then, @SmokingKilz .

**Comment by Ziiro** [comment]
+1 x 1000. I hate that thing.

**Comment by Cactus2388** [comment]
yes
that is all

**Comment by AdamElTablawy** [comment]
RIP the one counter to lich wizards

**Comment by Ralta** [comment]
Remove it for now. If someone had a better idea, by all means add it. But this thing is awful.
+1

**Comment by Quantum-M** [comment]
@FlattestGuitar , I think only metastation is the only map with the shard. And if someone is doing a rework for it, they can simply re-add it.

**Comment by SmokingKilz** [comment]
Yeah the rework is no longer just a simple switch, this can be merged. 


@AdamElTablawy Lich's can still be gibbed/cremated which is one of the most popular way people dispose of them anyway.

**Pull request merged**
