### PR TITLE
Adds 1 microbomb implant for Traitors to uplink.

### PR DESCRIPTION
**Pull request by EldritchSigma**
https://github.com/OracleStation/OracleStation/pull/381

Changelings are KOS. Cult gets deculted, Revs get killed or mindshielded. Traitors cannot suicide anymore effectivly with that PR above. And having witnessed that kind of bullshit on not getting killed even when asked and completly searched for a chembomb/toxbomb implant because of metaing the "Die." objective this should be a thing. Its a general dickmove of people to take their free choice of dying whenever they please. I should really ask... do people really have to make a voice activated toxin bomb and self implant it with ye olde self surgery glitch (yes there still is one) every fucking round they roll antag just to die when Sec inevadeably catches them? Perma is the most boring shit ever and considering there is still greentext and failtext in the game keeping someone alive because you metaed the "Die." objective is just a huge pile of bullshit. Apart from that I would take that kind of implant over being imprisoned any day, death is freedom, Flesh is a prison. Heck if TG code would have dust implants I would much rather use that, but alas its not there. I think 3 TC for this kind of implant is a fair price. Its about as potent as a improvised explosive. It really only gibs you. And noone forces you to respond to your brain in the MMI luckily.

:cl: EldritchSigma
add: Adds ultra low payload suicide bomb implants to traitor uplink for 3 TC. They can be triggered at will or on death. 
/:cl:

### CODE REVIEW

**Comment by Ziiro** [comment]
Even ignoring the suicide PR: I actually would like this in the game.

Question is: Does it go off with *deathgasp? Because a voice of god telling people to "PLAY DEAD" and one of them exploding is always great.

**Comment by EldritchSigma** [comment]
It should go off with *deathgasp. Its triggered by *suicide with like a 25% chance to fail. Always triggers on death and on activation. On *deathgasp it activates aswell I suppose.

**Comment by SamHPurp** [comment]
>Perma is the most boring shit ever

And when genpop is added....?

I think this is a out-of-proportion reaction. If you're perma'd there are still lots of ways to kill yourself, you just have to now do it yourself, not manage to cheat the whole process by typing a single word.

**Comment by EldritchSigma** [comment]
What ways on Omegastation? Cells are tiny with no stuff. Also its just a tiny suicide implant. Traitors buying it have less TC for more effective tools.

**Comment by EldritchSigma** [comment]
Could we get atleast a rule in place that prohibits sec from straightjacketing/permabucklecuffing you in perma so you atleast can kill yourself? Its just a plain out dickmove to meta your objective or just keep you alive "Just in Case they have the objective." despite you asking for execution/borging. Or atleast get some type of psych role so the perma prisoner would have something to do in case they get straightjacket bucklecuffed, even if its "just" talking.

**Comment by imsxz** [comment]
change the path for the uplink entry, it's using the same one as the Nukie one currently.

**Comment by SamHPurp** [comment]
@EldritchSigma 

>Could we get atleast a rule in place that prohibits sec from straightjacketing/permabucklecuffing you in perma so you atleast can kill yourself?

You cannot currently suicide while straight jacketed / cuffed, so that is an issue currently. (Although I don't think its an issue at all in actual fact).

I just don't see the need for this item at all tbh.

**Comment by EldritchSigma** [comment]
The item is to prevent people from making voice/health activated toxin bombs (or worse) for matyrdom/self destruction which usually result in more than just a few broken hull tiles, considering how easy it is to go overboard with a chembomb/toxin bomb. With this item they dont have an excuse to make any toxin bombs or gibsmoke bombs for self destruction (basicly anything that completly obliterates areas). It just would get the job done, destroy potential gear upon capture which the syndicate would not like to happen. It also prevents the creation of hazards towards other agents so thats a plus aswell.

**Comment by EldritchSigma** [comment]
Travis is a bitch atm as it was said in discord

**Comment by FlattestGuitar** [comment]
If you don't want to play, then just ghost. I kinda don't see the point behind this PR.

In my mind it only encourages more explosive martyrdom rather than stopping the people who'd go out of their way to make proper toxin bombs.

:-1:

**Comment by SamHPurp** [comment]
I think we're all agreed, and I have yet to see an arguement that holds enough water to add this.

**Pull request closed without merging**
