### PR TITLE
Shameless drone buffs

### PR DESCRIPTION
**Pull request by ike709**
:cl: ike709
tweak: Drones are now slightly faster, and can escape being a hat faster.
/:cl:

Makes it slightly less painful to be kidnapped and turned into a hat. Do you know how long the average spessman stands still for? Not five seconds.

Drones are also a bit faster. It's not sanic speed, I was just very annoyed by how painfully slow they were during drone hatch testing.

### CODE REVIEW

**Comment by Ziiro** [comment]
Paradise has an instant pickup and instant resist free. I'm a fan of the instant escape, mostly. Especially since crew has no meaningful interactions with drones besides being dicks anyway.

**Comment by ike709** [comment]
I'd like to do instant escape but I figured maintainers would yell at me.

**Comment by Ralta** [comment]
Instant would be good. I sometimes carry drones on my head onto the shuttle but if you have work to do, you should be able to escape immediately.

**Comment by SamHPurp** [comment]
Why do they need to be faster? I haven't seen a good arguement for that yet.

**Comment by ike709** [comment]
1. They're currently slow as fuck. If there's a breach or a fire or something they should be able to respond in a somewhat timely manner.
2. They need to escape the evil hat-wearers.
3. Why *shouldn't* they be faster?

And it's not like this makes them zoom across the station at lightspeed.

**Comment by AndrewMontagne** [comment]
IMO we can always revert this if it ends up being too OP or whatever.

**Pull request merged**
