### PR TITLE
Brings old ID sprites back

### PR DESCRIPTION
**Pull request by AffectedArc07**
**PREEMPTIVE DISCLAIMER:**
I know that the current IDs had a lot of time put into spriting, and the whole ground system was added, which this is rendering useless.

This PR changes the ID sprites to the ones flattest sprited a while ago. The reason for this is the current IDs dont match anything else in the code, and dont really fit the SS13 aesthetic (In my opinion). A discussion on this would be greatly appreciated before this is merged or closed.

All the cards for those who want them:
image

Take a look at this for example:
image

Notice the emag following the original ID sprite. Its designed to look like an ID with some circuit crap stuck to it, and with the current IDs it just doesnt fit. Someone attempted to sprite a new emag, it didnt work due to the limits of the newer sprites. 

My main other gripe with the current IDs is the lack of detail on them. 
image
image

Take these sprites for example. The older one has so much more detail, more vibrant colors, and generally looks nicer that its newer sprite. Not to mention the newer sprite having a large mass of wasted space, and the only "aesthetic" on them being the NT logo.

:cl: AffectedArc07
tweak: Changes the ID sprites to the ones flattest sprited a while ago. The reason for this is the current IDs dont match anything else in the code, and dont really fit the SS13 aesthetic (In my opinion)
/:cl:

### CODE REVIEW

**Comment by DaveTheHeadcrab** [comment]
Old ID cards are noisy and visually cluttered. Simple design does not mean lack of detail.

**Comment by DaveTheHeadcrab** [comment]
Also the vote was clear. Why do Eueopean children hate democracy?

**Comment by FlattestGuitar** [comment]
As mentioned on the PR that initially added them, I guess we're doing that "feedback" now.

I'm super biased because those were my sprites, but I'm definitely in support of this one being merged.

We'll need a solid way to figure out which version has more public support. Any ideas?

**Comment by AffectedArc07** [comment]
@FlattestGuitar typeform

**Comment by DaveTheHeadcrab** [comment]
Also, for the record, I had a new emag. It's in the code. I had to disable it as a concession to get the PR merged, but functionally and visually it was fine.

**Comment by FlattestGuitar** [comment]
> emag

I'm pretty sure it was disabled exactly because it was not fine visually. It looked like another ID, just with different text on it.

**Comment by Ralta** [comment]
I originally liked this one more. Now I'm...not really sure. A side-by-side comparison would probably help.

**Comment by FlattestGuitar** [comment]
Assistant, Captain, Head of Security.

**Comment by AndrewMontagne** [comment]
Following discussions with the other maintainers, we have decided to keep the current sprites.

**Pull request closed without merging**
