### PR TITLE
Renames IAA gamemode in preparation for IAA role

### PR DESCRIPTION
**Pull request by ike709**
:cl: ike709
tweak: The Internal Affairs gamemode has been renamed to Sleeper Agents in preparation for the Internal Affairs Agent role.
/:cl:

A while back TG redesigned and renamed the Double Agents gamemode to Internal Affairs Agents. Since the IAA role is planned, that would cause a lot of confusion, probably. So I renamed it.

Note that this does edit the config.

Also, be warned that this was mostly done with a mass find & replace.

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
I am okay with this.

**Comment by SamHPurp** [comment]
This is likely to require SQL query to fix up the database, no?

Agree with concept though - have you tested things out to make sure nothing breaks?

**Comment by ike709** [comment]
Seems to be fine in testing.

**Comment by ike709** [comment]
Reminder that this is somewhat necessary for the IAA role to be added.

**Pull request merged**
