### PR TITLE
New latejoin selection screen

### PR DESCRIPTION
**Pull request by FlattestGuitar**
Speaks for itself.
Feedback welcome.

Mostly from Paradise. Can't be bothered to look for the PR/commit.

:cl: Flatty
add: Fancy new latejoin Job Selection Screen
/:cl:

No, this is not made with AndrewUI.
No, I will not stop calling it AndrewUI.

### CODE REVIEW

**Comment by Ziiro** [comment]
`>clown isn't flagged as high priority`

**Comment by Quantum-M** [comment]
I think the AI job should be bolded, and the HoP one seems to be missing (unless it's taken).

Looks very neat and nice though.

**Comment by FlattestGuitar** [comment]
HoP is indeed taken on that pic. I couldn't be bothered to varedit the priority jobs.
Also, AI is not a command position, and that's the only reasoning I used for the boldening. It's technically snowflaking to make it bold, so I don't condone this.

**Comment by SmokingKilz** [comment]
Looks great, well done my g.

**Comment by SamHPurp** [comment]
Looks good.

But tbh, we should be robustly testing OracleUI #702 and moving everything to that, rather than developing and merging PRs that use nano

**Comment by AndrewMontagne** [comment]
@SamHPurp This does not use nano/tgui, fyi.

**Comment by Ralta** [comment]
It does look really nice. +1

**Comment by AffectedArc07** [comment]
On a sidenote, does AndrewUI support the coloring of buttons, text, progress bars

**Pull request merged**
