### PR TITLE
Port package wrap, first aid kits, briefcases from CEV Eris.

### PR DESCRIPTION
**Pull request by AndrewMontagne**
image

I modified the medkit sprites to be colour co-ordinated with the type of damage they fix, and made sure the in-hand sprites were also fixed.

:cl:AndrewMontagne
imageadd: Port package wrap, first aid kits, briefcases from Eris.
fix: Fixes issue with wrapping paper icons.
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
Gonna be a major killjoy. Can we use a different colour for the cross on two red ones somehow?

**Comment by FlattestGuitar** [comment]
What Purp said. Green will work fine.

**Comment by Spartan6** [comment]
Gotta obey that Geneva international law. Down with red crosses.

**Comment by FlattestGuitar** [comment]
>literally a war crime

**Comment by AndrewMontagne** [comment]
@SamHPurp Resolved.
image

**Comment by FlattestGuitar** [comment]
Also, I like the satchel sprite, but it's really different in terms of style from the other satchels and backpacks. This is pretty bad inconsistency. :c 

I'd say we should come up with sprites for other stuff before we add the satchel itself.

**Comment by AndrewMontagne** [comment]
@FlattestGuitar The leather satchel already looks inconsistent from the rest of the other sprites as the old one is a scaled down cropped photograph. >:C

**Comment by FlattestGuitar** [comment]
Now that I look at it, you're totally right. I guess I just got used to it. :v 

Let's still put some sort of a priority on redoing the backpacks and satchels in the near future, still.

LGTM.

**Pull request merged**
