### PR TITLE
pAI hatches and Ventcrawling!

### PR DESCRIPTION
**Pull request by Affurit**
:cl:
add: pAI can now use door hatches like drones!
add: pAI can now vent crawl!
/:cl:

Requested by the community.

### CODE REVIEW

**Comment by Affurit** [comment]
Aaaaaah?

**Comment by FlattestGuitar** [comment]
No

**Comment by FlattestGuitar** [comment]
Having your personal validhunt machines was never the intent of pAIs existing and it won't be now. Since I doubt anyone on the staff team will agree with this I'll save you the pain of trying to get this working.

I'm sorry for being harsh, but can you people stop going on about buffing pAIs

**Comment by Affurit** [comment]
I would just like to note that this wasn't my idea and it did work without any issues when testing...

**Pull request closed without merging**
