### PR TITLE
Adds Brig Physician Area In Brig

### PR DESCRIPTION
**Pull request by AffectedArc07**
image

I know it looks bland and I feel I fucked up on the mapmerge

:cl: AffectedArc07
del: Removed interrogation room
add: Added brigbay
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
I need a before photo... but my immediate thought is.... to big, too secure, and too many sleepers.

**Comment by SamHPurp** [comment]
Also Meta has an existing brigbay... what have you done with that space?

**Comment by AffectedArc07** [comment]
Meta doesnt have a brigbay?

**Comment by AffectedArc07** [comment]
Brigbay already "exists" and my brigbay sucks

**Pull request closed without merging**
