### PR TITLE
Adds a map to the PDA

### PR DESCRIPTION
**Pull request by AffectedArc07**
Added a way to view the map of the current station, right from your PDA. It will automatically pull the correct map, depending on the current station loaded. 

Main Menu:
image

image

Possible issues with acceptance of this PR:
- Webmap is not hosted by Oracle itself

:cl: AffectedArc07
add: You can now view the current station map on your PDA
/:cl:

Why: People ask what is this map, also useful for engineers to see wiring grid.

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
We will need to either host the webmap ourselves or use the preexisting crew monitor thingy.

The webmap is way prettier, but it requires updating by hand, while the crew monitor map is uggo, but is generated on its own.

What do you think, random people on our GitHub?

**Comment by Quantum-M** [comment]
Crew monitor would probably be easier, but it's rather laggy at times when you open it, no idea how a webmap would be like performance wise.

**Comment by FlattestGuitar** [comment]
image
Use this pic tho.

**Comment by AffectedArc07** [comment]
New icon:
image

**Comment by Cactus2388** [comment]
The crew monitor map is pretty laggy not sure how laggy this would be either.

**Comment by ShattForte** [comment]
I can see this being extremely helpful to engineers, as you can see the pipe/wire work. Makes repairs a breeze, I already keep DM open with the current map but if this was in the game it'd bypass the extra work.

**Comment by SamHPurp** [comment]
This seems like it'd be lagging, put extra strain on things, and links to non-server owned space.

👎

**Comment by FlattestGuitar** [comment]
Well, we could host the webmap ourselves...

Still, odd that we wouldn't use the already existing map rendered for the crew monitor.

Not sure what to do here, to be honest. 🤔

**Comment by AffectedArc07** [comment]
We can use the existing map, but you can already guess how shit the quality will be

**Comment by AffectedArc07** [comment]
https://github.com/OracleStation/OracleStation.github.io/pull/6

**Comment by SamHPurp** [comment]
This isn't something we want, after many discussions.

Do come talk to me and we can cover all the reasons again. Sorry AA

**Pull request closed without merging**
