### PR TITLE
Moves the clowns instrument horn to lavaland loot

### PR DESCRIPTION
**Pull request by SamHPurp**
We had much adjacent debate, this was proposed and nobody disagreed at the time.

Thoughts?

:cl: Purpose
del: Clown no longer starts with his instrument horn.
add: Gilded horn added as Lavaland loot.
/ :cl:

### CODE REVIEW

**Comment by imsxz** [comment]
I agree with the change but I don't think I've ever seen the clown planet biodome. Is it even able to be spawned? Can we replace beach bums with clown planet? :clown:

**Comment by SamHPurp** [comment]
@imsxz I've seen it multiple times. Its a larger one, so it eats more of the budget (if I understand the system)

**Comment by imsxz** [comment]
Ah alright. In that case, I support blacklisting beach bums so it stops stealing the budget from potential clown planet. No, I don't like beach bums >:^(

**Comment by SamHPurp** [comment]
Gnarly

**Comment by SamHPurp** [comment]
[Move the Gilded Bikehorn off of clown at round start.](https://trello.com/c/MOndSHnV/90-move-the-gilded-bikehorn-off-of-clown-at-round-start)

**Comment by ktoma36** [comment]
Idk, beach bums can be interesting, but I would much rather have more hermits. Beach bums have a pretty good base of operations though with the booze dispenser. A good barkeep could easily make some healing drinks. Also it has a sink, meaning that they can actually make leather (one of the few areas that you can clean skinned hide at).

**Comment by SamHPurp** [comment]
Beach bums is very much off topic

**Comment by ktoma36** [comment]
Yaya, sorry. The clown horn instrument being in that clown biodome would make it extremely rare to see, which isnt a bad thing persay but personally I stay clear of that area. Maybe adding it to a space ruin as well? That way a clown could possibly get a space pod (when we get those) and find the horn their self if the miners can't get em one

**Pull request merged**
