### PR TITLE
Metastation Robotics Improvements

### PR DESCRIPTION
**Pull request by Ziiro**
Never done a map edit. Something might be fucked up here. 🤔 

:cl: 
add: Posibrain to Robotics
add: Ripley boards to Robotics (One set)
add: Cautery to robotics surgery
tweak: Moves drone fabricator from the show room to robotics 
/:cl:
dreamseeker_2018-01-28_18-14-04

[why]: These give robotics something to do while waiting for R&D to get their shit together. It also allows them to manage the drone fab.

### CODE REVIEW

**Comment by Ziiro** [comment]
Needs a map merge. gotta learn a new skill.

**Comment by Ziiro** [comment]
After a brief discussion I might be moving the drone fab to INSIDE of robotics. Or the mechbay

**Comment by FantasticFwoosh** [comment]
Posibrain is over the top for technological data, it will be instantly cannibalized by RnD mains @Ziiro for its biological and computer programming technology.

/tg/ RnD machines aren't upper end restricted to manipulators more like they used to be for the complexity of items put inside.

**Review by FlattestGuitar — DISMISSED** [review]

**Comment by Ziiro** [comment]
DAMMIT, NO, I NEED TO MOVE THE DRONE FAB. THERE HAS JUST BEEN NO TIME FOR ME TO WORK ON THIS PR.

**Comment by AndrewMontagne** [comment]
Let me know via Discord when you've had time to work on this, @Ziiro.

**Comment by Ziiro** [comment]
dreamseeker_2018-02-01_21-28-10

**Review by AndrewMontagne — DISMISSED** [review]
LGTM

**Comment by SamHPurp** [comment]
I don't think I agree with the adding the posibrain to robotics tbh - why is this needed at all?

**Comment by Ziiro** [comment]
Robotics has zero work until R&D has done something. This fixes that with the Ripley boards, and the posibrain - a mech and a borg. Even if R&D shits the bed - as they have in every single round I have not played scientist myself - you could at least be doing *something* at roundstart.

If your major objection is like Fwoosh's, I can get rid of it.

**Comment by SamHPurp** [comment]
@Ziiro yeah 'fraid I echo @FantasticFwoosh 's concern.

**Comment by FlattestGuitar** [comment]
Will they, though?

I've had a ton of experience on Paradise and I've never seen that happen once, despite the posibrain being pretty darn useful. It's a crappy comparison, but it's the only thing we can base reasoning on.

**Comment by Ziiro** [comment]
As someone who often does R&D, let's check this out.

`origin_tech = "biotech=3;programming=3;plasmatech=2"`

So this is a nice boost, yes. But really not worth throwing off my nicely organized list for. You can deconstruct drone shells for bio 5. Or, you know, monkey organs.

Data theory and Plasma aren't that bad to raise either, but I don't recall the best trick to do so off the top of my head.

**Comment by Keluandrie** [comment]
Speaking as one who's done much, much RnD, those levels aren't even worth leaving my autism cave for. Plasma 3 is usually gotten within the first 3 items with a welder and flamethrower, with data and bio not far behind.

**Comment by ike709** [comment]
I just want the drone dispenser in robotics...

**Comment by SamHPurp** [comment]
Cautery to Robotics? Great that was an oversight?

Drone fabricator to Robotics? Sure no problem!

Ripley and Posibrain though, I fundamentally disagree with, this is strengthening the crew and antagonists a lot at round start, as opposed to delaying their impacts.

If you rip those two bits out, we can merge this,.

**Comment by Ziiro** [comment]
dreamseeker_2018-02-11_15-33-17

**Comment by Ziiro** [comment]
FUCKING BROKEN ASS MAPMERGE

**Pull request closed without merging**
