### PR TITLE
Big Friendly Button

### PR DESCRIPTION
**Pull request by AndrewMontagne**
image
image

:cl: AndrewMontagne
add: Big, Friendly Help Button
del: Report Issue Button
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
I'd sometimes tell people to use that button. I think it should stay....

**Comment by AffectedArc07** [comment]
I kinda see flattests point, maybe replace one of the other ones, or build report issue into the github one in a menu like "Are you reporting an issue or just visiting?"

**Comment by FlattestGuitar** [comment]
Maybe make the menu be a bunch of choices, like "Report a bug", "Ask gameplay question", "Report a violation of the rules", "Suggest a feature", "Ask for antag".

**Comment by ike709** [comment]
^

Not necessarily the choices I'd put, but it's a good idea.

**Comment by AffectedArc07** [comment]
@FlattestGuitar make the ask for antag button instagib you.

**Comment by Cactus2388** [comment]
Can you give it a hotkey? Not being able to f1 for adminhelp hurts me.

**Comment by ike709** [comment]
rip

**Pull request closed without merging**
