### PR TITLE
Removes Ethari completely from the game

### PR DESCRIPTION
**Pull request by Wilchenx**
🆑Wilchen
del: Removes ethari mutation toxin from the game.
/🆑

This sort of stuff is cringy and, frankly, rather creepy. It also has no place in a server attempting to achieve mid RP.

### CODE REVIEW

**Comment by Quantum-M** [comment]
Rather familiar reasons, like, reminds me of that cat girl removal PR.

**Comment by AffectedArc07** [comment]
Same reason at the cat ear removal PR, also they are already disabled, this is way more effort than required.

**Comment by Wilchenx** [comment]
>Same reason at the cat ear removal PR, also they are already disabled, this is way more effort than required.

I was told on discord people are still able to get the toxin.
Also this is just commenting out a few lines of code.

**Comment by AffectedArc07** [comment]
Add a configuration option to disable the mutation toxin, if we ever rework them this is going to be a huge pain

**Comment by Wilchenx** [comment]
>Add a configuration option to disable the mutation toxin, if we ever rework them this is going to be a huge pain

How is that going to be a huge pain for reworking them if its just commented out code that doesn't change the species  **at all**

as for #1071 the change is literally so small they can just edit their file and it will probably take less than a minute.

**Comment by FlattestGuitar** [comment]
Considering the author of this PR just got the hammer, I'll be closing it. 

Personally, I think the current state of things is fine, but if anyone wants to, they are free to reopen the PR from their own branch to resume the conversation.

**Pull request closed without merging**
