### PR TITLE
Adds plastitanium wall smoothing and plastitantium windows

### PR DESCRIPTION
**Pull request by Ziiro**
:cl: WJohnston & ninjanomnom
add: Plastitanium walls smooth, fancier syndicate shuttles!
/:cl:

[why]: # Needed for a future PR I was planning to port. And they look much nicer.

Ports https://github.com/tgstation/tgstation/pull/31410 mostly.

dreamseeker_2018-02-26_22-46-14

### CODE REVIEW

**Comment by Ziiro** [comment]
Okay, something fucked up with that Meta map merge. It should not be removing and re-adding that many lines. Fuck I hate mapping.

**Comment by Ziiro** [comment]
No more map changes. Just smoothing and sprite changes. Map changes in subsequent PR.

**Review by AndrewMontagne — APPROVED** [review]
LGTM

**Comment by SamHPurp** [comment]
IIRC there are loads and loads of fixes that were required for this. It might have all been mapping related, but just an FYI.

**Comment by Ziiro** [comment]
This is just the walls. The syndicate base is a separate PR.

**Pull request merged**
