### PR TITLE
Adds an incredible title screen; created by Fei Hazelwood

### PR DESCRIPTION
**Pull request by FlattestGuitar**
Literally this.

A M A Z I N G

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Yesssssss

**Comment by SamHPurp** [comment]
Think its cool, I think the animation cheapens it a little, but maybe I'm on my own there.

👍 though

**Comment by Birdtalon** [comment]
merge

**Comment by FlattestGuitar** [comment]
See, I'm sorta inclined to agree with @SamHPurp here, but I really want something moving in there, but my artistic skills are comparable to those of a really ugly sunflower and sunflowers don't have artistic skills.

**Comment by SamHPurp** [comment]
~~@FlattestGuitar very slight distant rotating clown~~

**Comment by FlattestGuitar** [comment]
Don't merge it for now. I'll fiddle around with some effects to hopefully make it better when I get some time. 

Feel free to do so yourself until then, but no merging.

**Comment by Quantum-M** [comment]
It's amazing, the the dark colors, twisted looking station and the glitch like animation conveys that something is wrong with the place, which pretty much is true.

**Comment by FlattestGuitar** [comment]
*inhale*

**Pull request merged**
