### PR TITLE
Ports Paradise ID Card Sprites

### PR DESCRIPTION
**Pull request by AffectedArc07**
:cl: AffectedArc07
add: Ported the paradise ID card sprites
tweak: Jobs now spawn with appropriate department ID cards
/:cl:

**IGNORE THE FIRST COMMIT, I BROKE MY FORK OK?!**

All jobs now spawn with relevant ID cards, Some of the sprites are unused, as this is a direct rip from para, in terms of sprites. This has been tested and it works.

Before:
image

After:
image

### CODE REVIEW

**Comment by SmokingKilz** [comment]
I agree, +1 from me.

**Comment by AndrewMontagne** [comment]
It would be nice if you went through and applied these to the relevant ID cards.

**Comment by AffectedArc07** [comment]
I will do that tomorrow, as its 22:51

**Comment by AffectedArc07** [comment]
Jobs now spawn with ID the relevant ID cards, this has been tested and it seems to work

**Pull request merged**
