### PR TITLE
Removes the beach biodome

### PR DESCRIPTION
**Pull request by imsxz**
:cl: imsxz
del: deletes lavaland_biodome_beach.dmm
del: removes the beach bum and beach bartender spawners
del: removes the beach biodome template from lavaland.dm
tweak: removes beach biodome from the config
/:cl:

I know this is going to to be downvoted and mocked, so I don't ask you to believe it, only to remember it.

You all have absolutely no idea how big of a mistake you're making to support the current beach biodome. It's a network of psychopaths- the sudden emergence of beach stoners is like the arm of this station, and it's a gradual psychological take over of our station. They've brainwashed you, and you're helping to march them straight into power where they will destroy day to day life as you know it once they are there. Their entire narrative and M.O is marijuana and parties, aka psychopath. I've spent years infiltrating various communities, darkweb forums they use, etc, and I absolutely promise you you are a making a mistake you will regret. I worry that it's too late. My only solace is that one day, you WILL inevitably realize that I am right.

### CODE REVIEW

**Comment by scrubmcnoob** [comment]
are you high writing this

**Comment by taukausanake** [comment]
Might as well remove Hydroponic drugs while you're at it then

**Comment by deep-fried-faceplant** [comment]
Is this just to make more room on Lavaland for loot and monsters?

**Comment by imsxz** [comment]
this PR was made because literally nobody ever spawns in as the beach bums, they're not enjoyable to play as or with.

**Comment by SamHPurp** [comment]
I quite like them personally.

Also this is the wrong way to do this, at least for the moment - but you can disable individual ruins from proc'ing in the config files.

**Comment by imsxz** [comment]
I'm fairly firm on the belief that they don't add anything to the game.

To start, I'll go over the stuff that doesn't really matter.

As a threat: That goes without saying, they don't provide a threat to anything.

As loot: Again, nothing, but that goes without saying either.

Now for the stuff that actually matters.

As a role for ghosts: They don't have anything to actually do, or any goal to really work to. All other lavaland ghost roles have a goal or activity to do, I can list them if it's REALLY wanted.

And finally, they don't give any interaction with miners. At most, they'll get a drink from the bartender or something. To make matters worse, the beach bums speak some stoner language or some shit that you need space drugs to understand.

:salt:

**Comment by imsxz** [comment]
Also what the h*ck is Travis failing for?

**Comment by SamHPurp** [comment]
Because you're removing shit that is being used still.

```loading RandomZLevels/beach2.dmm
_maps/RandomZLevels/beach2.dmm:281:error: undefined type: /obj/effect/mob_spawn/human/bartender/alive
_maps/RandomZLevels/beach2.dmm:285:error: unknown type```

Also, I still maintain that this is the wrong way to do it. If we want it not to spawn anymore, we should simply make the config change.

My reasoning for keeping it, is because I know how much people enjoy the 'ghost bars' on other servers... and this perfectly fits that.

**Comment by imsxz** [comment]
Fair enough reasoning on keeping it.

Would a config change be something to handle in a pull request, or would that be something that's changed specifically from the server? If it's the latter, I'll just leave this up until we get some more opinions and stuff, and we can simply blacklist it like you suggested. If it's the former, I'll revert most of the changed and just blacklist it.

**Comment by imsxz** [comment]
Thinking about it from other prespectives, I now agree with what purpose said. this was a very selfish pull request that wasn't very thought through, and I have since changed my mind.

**Pull request closed without merging**
