### PR TITLE
Conveyor update

### PR DESCRIPTION
**Pull request by Citinited**
This is a port of my own work from paradise: https://github.com/ParadiseSS13/Paradise/pull/9178

Why?: This PR's aim is to improve the current conveyor system. If you've ever made a conveyor belt that was longer than a short stretch, you'll know how infuriating they are to get right. I aimed to fix those issues in this PR.

List of changes:
- New sprites! These sprites make the direction of the conveyor belt really obvious, which means they are very, very easy to orient correctly.
- Conveyor belts will now automatically create corner pieces for you (see the .mp4 below).
- You can click a belt directly with a lever to link them.
- Clicking the ground with a conveyor belt construct will spawn a conveyor that faces your direction. This also applies to the conveyor belt placer.
- Removed levers will keep their ID instead of assigning a new one.
- Removed the "broken" sprite - AFAIK nothing makes conveyors broken, so I didn't bother with spriting these.
- Unpowered conveyor levers will no longer have a lit light.
- Loose conveyor switches have had their sprite slightly changed to help differentiate them from actual levers. (They looked exactly the same before)
- Added a conveyor lever to the lighthouse shuttle, seemed weird that it didn't have one

I've left all of the old sprites in the .dmi file, in case anyone wants to use them in future.

**Pictures!**

Loose lever and loose belt: image

A .mp4 of how the new sprites look can be found here: https://imgur.com/a/ZPuQIzg

A .mp4 of improved belt rotation: https://i.imgur.com/ZvoQ2d9.mp4

There are a bunch of map commits here so that I don't die in mapmerge hell when this PR inevitably conflicts with stuff 🎉 

:cl:
imageadd: Conveyor belts have received a facelift!
tweak: Rotating a belt with a wrench now nicely rotates the belt for you
tweak: Click a lever with a lever to link their IDs. Click a belt with a lever to link that belt to that lever.
tweak: Added a conveyor lever to the lighthouse shuttle
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
You added a lot of sprites, but never removed the old ones. Please do that as well!

**Comment by Citinited** [comment]
Old sprites removed

**Comment by Quantum-M** [comment]
I think the plates on the conveyor belt, as in each different section, should be a slightly darker shade of grey.

**Comment by Citinited** [comment]
I might see how it looks, but I'd rather not have to recolour all these sprites if I can help it haha 😄 (unless there is a broad consensus that it looks better)

**Comment by FlattestGuitar** [comment]
Looking at the map diffs, ferry_lighthouse.dmm lost a lever somewhere in there. Fix pls

**Comment by Citinited** [comment]
Did it? I added one, can't see anything in the old about a conveyor lever

**Comment by FlattestGuitar** [comment]
Hurr durr

**Pull request merged**
