### PR TITLE
Adds Autismpherics

### PR DESCRIPTION
**Pull request by SamHPurp**
Ports from kevinz000 & duncathan on the upstream.

:cl: Purpose
add: Pipes can now be layered up to 3 layers.
fix: Filters no longer stop passing any gas through if the filtered output is full.
tweak: Portable air pumps can output to a maximum of 25 atmospheres.
/ :cl:

### CODE REVIEW

**Comment by ktoma36** [comment]
With multi tile piping will there be multi tile vents/scrubbers :D

**Comment by SamHPurp** [comment]
@ktoma36 Yep. Thats actually a feature. ;)

**Comment by ktoma36** [comment]
I mean being able to stack them with the connectors facing the same way

**Comment by SamHPurp** [comment]
[Add multi-layer piping](https://trello.com/c/jb72vdvT/81-add-multi-layer-piping)

**Comment by ConflagratedCanine** [comment]
Yus. Maintenance will be so pretty!

**Comment by EldritchSigma** [comment]
Topic not PC other than that its cool I guess

**Comment by SamHPurp** [comment]
image

This fully works from all tests I did.

Please pull it and test it out yourself.

**Comment by taukausanake** [comment]
Still can't say I like the pipe adapters. Might need better icons for them.

So do scrubbers and vents match up with waste/supply pipes by default or do they fix themselves depending on the pipe next to them?

**Comment by SamHPurp** [comment]
@taukausanake you set them to what layer you want them to be. There are currently 3 available layers.

**Comment by ktoma36** [comment]
Could it be possible to have scrubber and supply default to the upper and lower layers? Hmm, would have to play around with it to see how it feels. Would this mean that scrubbers and vents could be set to connect to only one of the levels? Also how will these interact with heat exchange pipes? Sorry if Im being inquisitive, I just wanna make sure nothing gets oversighted :D

**Comment by ktoma36** [comment]
Im off on saturday, I could try my best to break it in the name of progress!

**Comment by FlattestGuitar** [comment]
I fucked around with it on local and couldn't find any issues, but there's just *so much to check*. The code looks fine to me, but there's so much crap there that I'd probably miss anything out of order anyway.

Testmerge this tonight, I say!

**Comment by AndrewMontagne** [comment]
Checked it out and tested it. Seems to work. 👌

**Comment by AndrewMontagne** [comment]
Missed the testmerge comments. My bad. 🤔

**Comment by SamHPurp** [comment]
🎉

**Comment by taukausanake** [comment]
Just to make sure, the pipes are still in their previous layout, correct?

**Comment by SamHPurp** [comment]
@taukausanake there have been zero map edits.

For this to exist at round start, the maps would need to be updated.

Otherwise you can do all this inround.

**Pull request merged**
