### PR TITLE
Low RP Removal

### PR DESCRIPTION
**Pull request by Affurit**
:cl: 
del: Removed LowRP brain damage things.
/:cl:

It needed to be done.

### CODE REVIEW

**Comment by Ziiro** [comment]
brain damage lines are sacred, how dare you

**Comment by Affurit** [comment]
They will fall.

**Comment by Cactus2388** [comment]
It's in poor taste to remove these sacred memes

**Comment by AdamElTablawy** [comment]
quantum

**Comment by SamHPurp** [comment]
While I agree that some of these are dumb, your replacements aren't any better, tbh.

**Comment by Affurit** [comment]
Care for some constructive criticism or is that all you can spare? 

My changes remove the references and replace them with acceptable alternatives.

That’s all.

**Comment by Affurit** [comment]
I can clearly see now that this is exactly the type of atmosphere this server wants. Thank you for your very helpful reviews, friends.

**Pull request closed without merging**
