### PR TITLE
Makes Oracle More PC

### PR DESCRIPTION
**Pull request by FlattestGuitar**
Because we all get triggered by those too easily.

### CODE REVIEW

**Comment by SamHPurp** [comment]
Meatballs are literally called faggots in the UK though. I'd support keeping them. :p

**Comment by FlattestGuitar** [comment]
I believe removing faggots from this server will benefit everyone.

**Comment by Birdtalon** [comment]
I second @FlattestGuitar  on this.

**Comment by SamHPurp** [comment]
Alright, we've voting  you off the island @FlattestGuitar

**Comment by EldritchSigma** [comment]
desc = "Useful for autismforts"
 +	desc = "Useful in defensive applications which have nothing to do with mental disorders."

Hahahaha nice one.

**Pull request merged**
