### PR TITLE
Added wardrobes to arrival shuttle

### PR DESCRIPTION
**Pull request by RawrARawrz**
:cl:
add: Added 4 wardrobes to the arrival shuttle of OmegaStation
/:cl:

tgstation has it, so should this. And I want my god damn black bandana.

### CODE REVIEW

**Comment by SamHPurp** [comment]
I'm good for the concept, but you need to mapmerge please.

**Comment by FlattestGuitar** [comment]
https://github.com/OracleStation/OracleStation/tree/master/tools/mapmerge

Read the readme.md file in there. 

Also, who even are you, mysterious contributor?

**Comment by SamHPurp** [comment]
Please include an image, and we can merge.

**Comment by RawrARawrz** [comment]
gitwardrobes

**Pull request merged**
