### PR TITLE
Doubles vacuum damage

### PR DESCRIPTION
**Pull request by ghost**
Ports https://github.com/tgstation/tgstation/pull/32566

🆑 steamport, originally by nicn
balance: Damage from low pressure has been doubled.
/🆑

### CODE REVIEW

**Comment by spoonitate** [comment]
So the engineering department actually hauls ass to plug breaches I suppose?

**Comment by steamp0rt** [comment]
@spoonitate I've actually spacewalked from the AIsat exterior to escape, on Meta, with just salbumatol pills and brute patches

**Comment by kingoftheautism** [comment]
@steamp0rt Why not just use firesuit?

**Comment by steamp0rt** [comment]
@kingoftheautism Because it was a wormhole teleport?

**Comment by Ralta** [comment]
I'm okay with this. It makes you rethink space-walking in a big way, which shouldn't be nearly as 'easy' as it currently is.

**Pull request merged**
