### PR TITLE
Drone hatches II: The Hatchinator

### PR DESCRIPTION
**Pull request by FlattestGuitar**
No changelog, because we already have this in ours.

Just a simple issue with CanPass not returning parent proc's value.

### CODE REVIEW

**Comment by ike709** [comment]
```
/obj/machinery/door/CanPass(atom/movable/mover, turf/target)
	if(istype(mover))
		if(mover.checkpass(PASSGLASS))
			return !opacity
		if(density && has_hatch && mover.checkpass(PASSDOORHATCH))
			open_hatch(mover)
			return TRUE 
	return !density
```

**Comment by ike709** [comment]
I don't know how I fucked up copypasting that from the FTL13 PR, but I did.

**Comment by Ziiro** [comment]
Another quality PR by Ike

It was really funny to have the entire station screaming about their doors not working by the way

**Comment by ike709** [comment]
To be fair I tested it with drones and it worked fine for them... I just didn't test it with humans.
@Ziiro

**Pull request merged**
