### PR TITLE
Ports victorian clothing from paradise

### PR DESCRIPTION
**Pull request by Brasnak**
Ports the victorian clothing from paradise and adds them to the ClothesMate

:cl:
add: victorian style clothing
add: victorian style clothing to clothesmate
imageadd: icons and mob sprites for all victorian clothing
/:cl:

dreamseeker_2017-11-08_10-37-02
dreamseeker_2017-11-08_10-39-15

### CODE REVIEW

**Comment by SamHPurp** [comment]
Leading merge commit gross

**Comment by SamHPurp** [comment]
I know people like their snowflakes, but I don't like increasing the number of snowflakey outfits.

**Comment by FlattestGuitar** [comment]
I think those are fine. Those look really good and are hardly snowflaky compared to the other crap we have there.

**Comment by Xantholne** [comment]
Weren't they originally from somewhere else before Para?

**Comment by SamHPurp** [comment]
Guess I'm the only person against it

**Pull request merged**
