### PR TITLE
Adds defines for organ slots

### PR DESCRIPTION
**Pull request by scrubmcnoob**
ports tgstation/tgstation#31737

Porting their brain trauma rework before I do moodlets, want this done.

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
[this](https://github.com/scrubmcnoob/OracleStation/blob/master/code/game/gamemodes/changeling/evolution_menu.dm#L78)
[this](https://github.com/scrubmcnoob/OracleStation/blob/master/code/game/gamemodes/changeling/powers/regenerate.dm#L30)
[this](https://github.com/scrubmcnoob/OracleStation/blob/master/code/game/machinery/cloning.dm#L166)
[this](https://github.com/scrubmcnoob/OracleStation/blob/master/code/modules/mob/living/carbon/human/species.dm#L145)
[this](https://github.com/scrubmcnoob/OracleStation/blob/master/code/modules/surgery/organ_manipulation.dm#L82)
Examples of you not applying the new defines. I'd really rather this was consistent. You'll have to change those over. The ones I linked are only for the brain, not other organs, which I didn't bother to check, but I'd imagine they also miss multiple instances.

**Comment by scrubmcnoob** [comment]
Where are you getting this? I already did these files
https://github.com/scrubmcnoob/OracleStation/blob/dd9593f43d6dcccdf1c10c3d6f479ff2f712e60e/code/modules/mob/living/carbon/human/species.dm

That's the file change in the PR.
You linked this file
https://github.com/scrubmcnoob/OracleStation/blob/master/code/modules/mob/living/carbon/human/species.dm#L145
That's the wrong branch.

**Comment by scrubmcnoob** [comment]
Searched the whole project in atom for everything, that should cover it all.

**Comment by FlattestGuitar** [comment]
:v

**Pull request merged**
