### PR TITLE
Clockcult rework & Href admin security tokens

### PR DESCRIPTION
**Pull request by SamHPurp**
First commit ports https://github.com/tgstation/tgstation/pull/29741 & https://github.com/tgstation/tgstation/pull/30542

Second commit has https://github.com/tgstation/tgstation/pull/31044

Third commit is https://github.com/tgstation/tgstation/pull/31327

Fourth commit is https://github.com/tgstation/tgstation/pull/31503

Fifth commit is https://github.com/tgstation/tgstation/pull/31504

Sixth commit is https://github.com/tgstation/tgstation/pull/31757

Seventh commit is https://github.com/tgstation/tgstation/pull/31325

Eighth commit is https://github.com/tgstation/tgstation/pull/31421

Ninth commit is https://github.com/tgstation/tgstation/pull/31956

Tenth commit is https://github.com/tgstation/tgstation/pull/31723 & https://github.com/tgstation/tgstation/pull/31282

Eleventh commit is https://github.com/tgstation/tgstation/pull/32272

Twelfth commit is https://github.com/tgstation/tgstation/pull/32497

Thirteenth commit is https://github.com/tgstation/tgstation/pull/31244

Fourteenth commit is https://github.com/tgstation/tgstation/pull/31673

Fifteenth commit is https://github.com/tgstation/tgstation/pull/32274 & https://github.com/tgstation/tgstation/pull/32397 & https://github.com/tgstation/tgstation/pull/32445

Sixteenth commit is https://github.com/tgstation/tgstation/pull/30969 & https://github.com/tgstation/tgstation/pull/31038

Seventeenth commit is https://github.com/tgstation/tgstation/pull/29839

Eighteenth commit is https://github.com/tgstation/tgstation/pull/30891

Nineteenth commit is https://github.com/tgstation/tgstation/pull/30848

Twentieth commit is https://github.com/tgstation/tgstation/pull/30933

Twenty-first commit is https://github.com/tgstation/tgstation/pull/30931

Twenty-second commit is https://github.com/tgstation/tgstation/pull/30975

Twenty-third commit is https://github.com/tgstation/tgstation/pull/30983

Twenty-forth commit is https://github.com/tgstation/tgstation/pull/30984

Twenty-fifth commit is https://github.com/tgstation/tgstation/pull/30987

Twenty-sixth commit is https://github.com/tgstation/tgstation/pull/31089

Twenty-seventh commit is https://github.com/tgstation/tgstation/pull/31191

Twenty-eighth commit is https://github.com/tgstation/tgstation/pull/31666

Twenty-ninth, Thirtieth and Thirty-first commits are conflict resolution.

Thirty-second commit is https://github.com/tgstation/tgstation/pull/31063

Thirty-third commit is conflict resolution.

Thirty-forth commit is https://github.com/tgstation/tgstation/pull/30554

Thirty-fifth commit is https://github.com/tgstation/tgstation/pull/31330

Thirty-sixth commit is https://github.com/tgstation/tgstation/pull/30688

this was miserable.

:cl: Assorted TGStation coders, adapted by Purpose
add: Reworks Clockwork Cult.
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
Vomited labels

**Comment by imsxz** [comment]
Not sure if my review went through. Line 200 in slab_abilities.dm, knockdown value should be 150 instead of 15 (unless it's supposed to be a 1.5s stun)

**Comment by SamHPurp** [comment]
This was so unbelievably miserable to do.

**Comment by AndrewMontagne** [comment]
Oh god the DMI conflicts.

**Comment by SamHPurp** [comment]
*scream

**Comment by SamHPurp** [comment]
@FlattestGuitar @AndrewMontagne good to go now.

https://www.youtube.com/watch?v=79DijItQXMM

**Comment by FlattestGuitar** [comment]
May God have mercy on our souls

**Pull request merged**
