### PR TITLE
What the HECK

### PR DESCRIPTION
**Pull request by imsxz**
:cl: XTDM
add: Added the H.E.C.K. suit, a guaranteed loot frop from Bubblegum. The H.E.C.K. suit is fully fire (and ash) proof, and has very good melee armor. Despite spending centuries inside a demon king, H.E.C.K. suits are most definitely safe.
/:cl:

ports XTDM's #30525 - https://github.com/tgstation/tgstation/pull/30525

This is to give non-antags an incentive to kill bubblegum, as currently there's almost zero reason to kill him, as his loot is only useful to antags in most cases. Screenshots in the link above, spraypaint support not included though.

### CODE REVIEW

**Comment by SamHPurp** [comment]
Conflicts.

Also I'm porting the component system in another PR, so we could get the re-colourability etc soon. Makes sense to wait for that to be merged, then update this one with it, what do you think?

**Comment by imsxz** [comment]
ye that sounds good, I'll fix the conflicts when I remember to and then add the spray paint thing once your component PR is merged

**Comment by scrubmcnoob** [comment]
war is heck

**Comment by SamHPurp** [comment]
@imsxz it merged 🎉

**Comment by EldritchSigma** [comment]
Doom Guy suit

**Comment by imsxz** [comment]
what the heck i dropped my motivation to code stuff and cant find it anywhere why does this happen to me ahhhhhh

**Comment by SamHPurp** [comment]
:(

**Pull request closed without merging**
