### PR TITLE
Kill urself

### PR DESCRIPTION
**Pull request by FlattestGuitar**
:cl: Flatty
tweak: Double Agents will no longer get the objective to kill themselves. Relax at the bar instead.
tweak: Traitors will no longer get the objective to kill themselves; they get nothing instead. Still end your life if it floats your boat.
/:cl:

### CODE REVIEW

**Comment by Kokojos** [comment]
Is :tweaka: a valid tag? Typo if not.

**Comment by FlattestGuitar** [comment]
tweka

**Comment by SamHPurp** [comment]
Kinda changes a big part of the idea of the gamemode. Hrm

**Comment by FlattestGuitar** [comment]
Need your stance on this one, @SamHPurp, @SmokingKilz

**Comment by FlattestGuitar** [comment]
@SamHPurp, @SmokingKilz

I swear to God.

**Comment by Wilchenx** [comment]
Most fun antag rounds i had usually included die a glorious death, i'd be sad if its gone. It takes away from the gamemode. 

Also seeing the chaos you've wrought on the station is so fun.

**Comment by FlattestGuitar** [comment]
That remains unchanged, @Wilchenx. You're still free to go die if you wanna. The objective never gave you anything extra to complete the goal with or allowed for any additional carnage, as per our rules.

**Comment by SamHPurp** [comment]
I still don't understand the point tbh.

Is it widely thought of that these rounds get too chaotic or something?

**Comment by SamHPurp** [comment]
Lack of response, if you still want this, lets get some actual dialogue going, because this seems to be trying to fix a problem I don't yet recognise..

**Pull request closed without merging**
