### PR TITLE
Small Taser nerf

### PR DESCRIPTION
**Pull request by Ziiro**
:cl: Ziiro
tweak: Tasers have a slightly longer cooldown between firing
/:cl:

### CODE REVIEW

**Comment by SamHPurp** [comment]
As we discussed, this should also include the borg one, and maybe a real small one for the HoS gun (`5 deca`?)

**Comment by ike709** [comment]
Reminder that DM uses deciseconds, not decaseconds you dummies.

**Comment by Ziiro** [comment]
Borg hybrid tasers use the same `/obj/item/ammo_casing/energy/electrode` ammo, so they'll be affected too.

**Comment by SmokingKilz** [comment]
HoS' gun should def also take a small nerf.

**Comment by Ziiro** [comment]
It did. `delay = 5`.

Not much, but something.

**Review by FlattestGuitar — APPROVED** [review]

**Pull request merged**
