### PR TITLE
Booze machines don't need any access anymore

### PR DESCRIPTION
**Pull request by FlattestGuitar**
:cl: Flatty
tweak: Most booze-o-mats no longer require any access on your ID.
/:cl:

### CODE REVIEW

**Comment by Ziiro** [comment]
power creep

**Comment by Quantum-M** [comment]
I kind of disagree. For booze machines in maintenance or ones created later in the round, it would be fine, but the one in the actual bar I think should have access restrictions, as it will encourage people (aka greytide) to go over the counter and loot the machine if the bartender steps out for a moment.

**Comment by AdamElTablawy** [comment]
helps chemists make neurotoxin if they can just grab 5 bottles of the requisite and run instead of having to do back and forths for the booze dispenser, tbh

**Comment by SamHPurp** [comment]
Disagree with this. Built ones, sure, have no restrictions... but the actual one in the bar? No. This'll only encourage people to ignore the barkeep and jump the bar.

**Pull request closed without merging**
