### PR TITLE
Removes the "die a glorious death" objective.

### PR DESCRIPTION
**Pull request by FlattestGuitar**
A reopen of a part of #820.

This PR removes the `die a glorious death` objective from regular traitors.

This PR doesn't remove the interactions possible right now. You will now have one free objective slot instead of that old one, which means you yourself can choose to get yourself killed or escape on the shuttle. The "free slot" thingy has the same chance and prerequisites for being picked as the old objective.

Here's my reasoning:
* The objective makes it seem like you are allowed to do anything "glorious" (i.e. acts of terrorism) to complete it. That is wrong, and doing so is a breach of rules that might lead to a ban, as it already has, multiple times.
* Some people might not want to die and forcing them to choose between greentext and having their character survive the round is odd.
* People who want to powergame the objective to win will just silently kill themselves in maint, which is really uneventful.
* The only reasonable way to accomplish this objective in a manner that is interesting to you and other players is to specifically let Security kill you during a chase, which is so rare that we might as well let people choose whether to do it themselves.

:cl: Flatty
tweak: Removes the "Die a glorious death" objective from traitors
/:cl:

### CODE REVIEW

**Comment by The-Driker** [comment]
Yes please.

**Comment by Quantum-M** [comment]
I agree. People tend to presume that they can severely damage and murderbone the station.

Not many people are interested in killing themselves either.

**Comment by Wilchenx** [comment]
image

Damn i wonder if there is any connection here 🤔

**Comment by SamHPurp** [comment]
Conceptually: LGTM.

Didn't review the code though.

**Pull request merged**
