### PR TITLE
Changes the CC Official uniform to the not 8 year old one

### PR DESCRIPTION
**Pull request by Xantholne**
It was pretty disgusting honestly. The updated black and gold ones from Paradise are much better.
New
2cb8af632fc5cc5335a0f753a4bb2e1d
Current
e696786480d84656c4226ce651682ed7

Bask in it's vomit.

:cl: Xantholne
fix: The CC Official isn't 8 years old anymore
/:cl:

### CODE REVIEW

**Comment by imsxz** [comment]
update the centcom bedsheet too then, they have a similar style to the old jumpsuit.

**Comment by SamHPurp** [comment]
Can we get an image of the existing one for a side-by-side comparison?

**Comment by EldritchSigma** [comment]
The old one looks like goons captain armor.

**Comment by Joseph-Case** [comment]
I don’t like green being the captain and cc colours

**Comment by DaveTheHeadcrab** [comment]
Green is CC, blue is the Captain.
Don't really see an issue with the one we have right now.

**Comment by FlattestGuitar** [comment]
I support this PR. Eye-scorching green doesn't fit anywhere in the normal uniforms. The black CC outfits are pretty.

**Pull request merged**
