### PR TITLE
Mutation Toxin Rework

### PR DESCRIPTION
**Pull request by AndrewMontagne**
Reworked the mutation toxins to make them less memey and more useful for correcting people's species. This also adds a new bit of code to the reagents system which allows you to conditionally specify whether a chemical reaction can take place. In this case, it's used to check the species data of the blood. I also added species data to the blood reagent.

You can still get Ethari blood in blood pack freezers. Whether or not it spawns in there is random chance.

:cl: AndrewMontagne
add: Adds conditional logic to chemical reactions.
add: Adds species data to blood.
del: Removed recipes for golem, skeleton and zombie toxins.
tweak: Changed mutation toxins to require blood of the target species to create the relevant toxin.
tweak: Unstable mutation toxin will now only make you a slime.
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
Not a fan of the solution. It completely locks down the system. I preferred an absent green slime to start with.

~~Maybe the entirety of Science being removed?~~

**Comment by AndrewMontagne** [comment]
I can never please you, can I Flatty?

**Comment by AffectedArc07** [comment]
Can you add config options for which mutation toxins will work or not?

**Comment by AndrewMontagne** [comment]
TODO: Add a blood bag with random species DNA as a maintenance loot item/blood chest item

**Comment by Ledwin1233** [comment]
This is nice but whats with the removal of the recipes for golem, skeleton and zombie mutation toxins?

**Comment by Battletrap360** [comment]
Good Job Andrew! I like what I see!

**Comment by SamHPurp** [comment]
Less of an issue now but lets see how this works. I think this is slightly more interesting.

**Pull request merged**
