### PR TITLE
Readds za Stando for traitors. Holoparas are back

### PR DESCRIPTION
**Pull request by EldritchSigma**
TG readded them recently. We dont have those things back yet and I always thought the Holoparasites are pretty fun. Would like to discuss the costs in particular because I find that 18 TC are excessive considering you can get Carp and a pack of throwing weapons for a total of 20 TC and dont make you completly reliant on another person (or you know, a revolver and lots of expensive ammo from a hacked lathe, or an Emag for B&E and stuff, all cheaper than holoparas.)

Obligatory JoJo meme... za warudo toki yo tomare!

:cl: EldritchSigma
add: Very buff and tough Syndicate agents have been seen arround NT installations using ghost like Nanoswarms to bust open walls and do other incredible stuff. Crewmembers of those installations call them Guardians or Stands. They even claim that a blonde haired user with fangs stopped time with one of those Nanoswarms but said witnesses were probably high on space drugs because you cannot stop time.
balance: The price has changed. Boo.
/:cl:

### CODE REVIEW

**Comment by EldritchSigma** [comment]
Working on it

**Comment by EldritchSigma** [comment]
Fucking hell... I hate the spacebar/tab thing and that it makes a difference. Yeah latest commit passed the check. Thank fucking god it did. Did I tell you how much I hate the spacebar/tab thing?

**Comment by EldritchSigma** [comment]
Funny... I should add that Github desktop compiled the failed builds, now did try that again after I did some updates and... Yeah the failed builds dont work either anymore. Fucking hell.

**Comment by SamHPurp** [comment]
So you are porting: https://github.com/tgstation/tgstation/pull/31616 ?

Why have you lowered the price?

**Comment by EldritchSigma** [comment]
I lowered the price because I find it silly that you should pay 18 TC to give a ghost something to do which might be a total new player for an item that gives you no control about how potent it is. It is more expensive than carp... and carp lets you clean entire sec teams. Holopara not. You are still vulnerable to shots and all they have to do is either shoot your stando or you which they will do if you have a guardian. Its fairly overpriced at 18 TC and considering guardians are HIGHLY specific in roles (mostly combat oriented or crowd control) it doesnt leave open many options for tools. With 14 TC as a price you can atleast buy another tool or 2 to help you out with your traitorous deeds without giving your round completly into the skillset of another person. And considering we have half of TGs movement speed it is not nearly as broken since you can actually land hits on the stand or the host. With 14 TC you get an effective weapon or utility tool , and thats about it. 6 More TC for either your B&E go to tool (EMAG), some other helpfull tools (Radio Jammer comes to mind, or the severly underused dart gun with some poisons) or even a chameleon kit for the ultimate gimmick and turning yourself into a propper stand user. With 18 TC you have 2 left. Thats enough for: 1 Edagger, 2 Useless Fake Nuke Disk, 2 Toolboxes, 2 AI detectors, Syndicate Smokes, 2 Syndie Soaps, 2 Carp Plushies. Sure you have more punchghosts to choose from but that doesnt mean they excel at combat that good (or at utility) they warrant its initial ultra high 18 TC price. Additionally we have rules in place that do not allow murderboning except for hijack.

**Comment by Ziiro** [comment]
Holopara is such a wildcard.

Either you end up with guy who started last week and is an active detriment, or you end up with some Robust asshole that can actually play one to it's full potential.

It depends greatly on the playerbase.

I do like them a lot, though, and I would be happy to see them return.

**Comment by EldritchSigma** [comment]
I am open for suggestions regarding the holoparas. Especially the Dexterious one (I mean who the fuck has a dexbuild you fucking... SKELETON WARRIOR.). The Dex one for those who dont know can hold an item and use it (and even keep it when recalling). Its ultra strong for the "Steal the stupid Antique Laser Gun you wont get because Thali is a fucking comdom and takes it out the moment theres a confirmed threat on the station." objective since once you get your dirty hands on the gun your holopara can use it and you can safely store it. It can also use shotguns that way if I recall correctly. Its basicly a storage implant with one slot but the ability to help you in combat. I thought of increasing its damage transfer rate to balance that out. Any other ideas?

**Comment by FlattestGuitar** [comment]
I really dislike holoparasites. They suck 99% of the time and they can be stupidly powerful that other 1%. As Ziiro said, they're a massive wildcard, and something like this being super random will lead to a lot of salt. I'm okay with adding them here, but we really should look into making them more interesting and less random in the future.

**Comment by EldritchSigma** [comment]
Agreed Flattest. As I said if you have any ideas how to make them more interesting just call me here or on discord

**Comment by FlattestGuitar** [comment]
My idea I had back in the day for improving these was to make them really cheap, but also make their life be on a timer. You spawn in, faff around for five minutes and go out the window. 

A reduced price means that a useless holoparasite won't hurt as much and the lowered lifetime means that the antagonist is punished for making another player sit in their body for 90 minutes doing *NOTHING*.

We could make the non-tator holoparasites stay the way they are, since those aren't really used in the same situations as the Syndie ones.

**Comment by imsxz** [comment]
Holoparasites can be a wild card but in general they're pretty bad. They'll get a few kills, and inevitably get overwhelmed.

I've gotten a fair amount of holoparasites in my time playing ss13, and even with having some of the best players I know as my stand, they still usually get me killed.

Their best function and reason for purchasing IN MY OPINION is to teach new antags how to antagonize, like an IC mentor.

**Comment by Ziiro** [comment]
The few times I've played Holopara, I've enjoyed it for the above mentioned reason. Instead of just observing someone in as a ghost and saying "OH MAN, WHY DIDN'T THEY DO X?" you have an ability to collaborate and throw ideas back and forth with the tot and plan accordingly.

Plus it makes it a pretty social experience and adds to the roleplay.

**Comment by imsxz** [comment]
Oh yeah I forgot to mention its REALLY shitty to sign up for holopara only to get a host who's like "yeah today we're downloading research levels" and then you do nothing but idle around the entire round

**Pull request merged**
